// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lookup.proto
#ifndef GRPC_lookup_2eproto__INCLUDED
#define GRPC_lookup_2eproto__INCLUDED

#include "lookup.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace lookup {

class LookupService final {
 public:
  static constexpr char const* service_full_name() {
    return "lookup.LookupService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status KeyLookup(::grpc::ClientContext* context, const ::lookup::Key& request, ::lookup::Value* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lookup::Value>> AsyncKeyLookup(::grpc::ClientContext* context, const ::lookup::Key& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lookup::Value>>(AsyncKeyLookupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lookup::Value>> PrepareAsyncKeyLookup(::grpc::ClientContext* context, const ::lookup::Key& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lookup::Value>>(PrepareAsyncKeyLookupRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lookup::Value>* AsyncKeyLookupRaw(::grpc::ClientContext* context, const ::lookup::Key& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lookup::Value>* PrepareAsyncKeyLookupRaw(::grpc::ClientContext* context, const ::lookup::Key& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status KeyLookup(::grpc::ClientContext* context, const ::lookup::Key& request, ::lookup::Value* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lookup::Value>> AsyncKeyLookup(::grpc::ClientContext* context, const ::lookup::Key& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lookup::Value>>(AsyncKeyLookupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lookup::Value>> PrepareAsyncKeyLookup(::grpc::ClientContext* context, const ::lookup::Key& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lookup::Value>>(PrepareAsyncKeyLookupRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::lookup::Value>* AsyncKeyLookupRaw(::grpc::ClientContext* context, const ::lookup::Key& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::lookup::Value>* PrepareAsyncKeyLookupRaw(::grpc::ClientContext* context, const ::lookup::Key& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_KeyLookup_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status KeyLookup(::grpc::ServerContext* context, const ::lookup::Key* request, ::lookup::Value* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_KeyLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_KeyLookup() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_KeyLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KeyLookup(::grpc::ServerContext* context, const ::lookup::Key* request, ::lookup::Value* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestKeyLookup(::grpc::ServerContext* context, ::lookup::Key* request, ::grpc::ServerAsyncResponseWriter< ::lookup::Value>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_KeyLookup<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_KeyLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_KeyLookup() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_KeyLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status KeyLookup(::grpc::ServerContext* context, const ::lookup::Key* request, ::lookup::Value* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_KeyLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_KeyLookup() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::lookup::Key, ::lookup::Value>(std::bind(&WithStreamedUnaryMethod_KeyLookup<BaseClass>::StreamedKeyLookup, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_KeyLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status KeyLookup(::grpc::ServerContext* context, const ::lookup::Key* request, ::lookup::Value* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedKeyLookup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::lookup::Key,::lookup::Value>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_KeyLookup<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_KeyLookup<Service > StreamedService;
};

}  // namespace lookup


#endif  // GRPC_lookup_2eproto__INCLUDED
