// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router.proto

#ifndef PROTOBUF_router_2eproto__INCLUDED
#define PROTOBUF_router_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
namespace google {
namespace protobuf {
class DescriptorProto;
class DescriptorProtoDefaultTypeInternal;
extern DescriptorProtoDefaultTypeInternal _DescriptorProto_default_instance_;
class DescriptorProto_ExtensionRange;
class DescriptorProto_ExtensionRangeDefaultTypeInternal;
extern DescriptorProto_ExtensionRangeDefaultTypeInternal _DescriptorProto_ExtensionRange_default_instance_;
class DescriptorProto_ReservedRange;
class DescriptorProto_ReservedRangeDefaultTypeInternal;
extern DescriptorProto_ReservedRangeDefaultTypeInternal _DescriptorProto_ReservedRange_default_instance_;
class EnumDescriptorProto;
class EnumDescriptorProtoDefaultTypeInternal;
extern EnumDescriptorProtoDefaultTypeInternal _EnumDescriptorProto_default_instance_;
class EnumOptions;
class EnumOptionsDefaultTypeInternal;
extern EnumOptionsDefaultTypeInternal _EnumOptions_default_instance_;
class EnumValueDescriptorProto;
class EnumValueDescriptorProtoDefaultTypeInternal;
extern EnumValueDescriptorProtoDefaultTypeInternal _EnumValueDescriptorProto_default_instance_;
class EnumValueOptions;
class EnumValueOptionsDefaultTypeInternal;
extern EnumValueOptionsDefaultTypeInternal _EnumValueOptions_default_instance_;
class FieldDescriptorProto;
class FieldDescriptorProtoDefaultTypeInternal;
extern FieldDescriptorProtoDefaultTypeInternal _FieldDescriptorProto_default_instance_;
class FieldOptions;
class FieldOptionsDefaultTypeInternal;
extern FieldOptionsDefaultTypeInternal _FieldOptions_default_instance_;
class FileDescriptorProto;
class FileDescriptorProtoDefaultTypeInternal;
extern FileDescriptorProtoDefaultTypeInternal _FileDescriptorProto_default_instance_;
class FileDescriptorSet;
class FileDescriptorSetDefaultTypeInternal;
extern FileDescriptorSetDefaultTypeInternal _FileDescriptorSet_default_instance_;
class FileOptions;
class FileOptionsDefaultTypeInternal;
extern FileOptionsDefaultTypeInternal _FileOptions_default_instance_;
class GeneratedCodeInfo;
class GeneratedCodeInfoDefaultTypeInternal;
extern GeneratedCodeInfoDefaultTypeInternal _GeneratedCodeInfo_default_instance_;
class GeneratedCodeInfo_Annotation;
class GeneratedCodeInfo_AnnotationDefaultTypeInternal;
extern GeneratedCodeInfo_AnnotationDefaultTypeInternal _GeneratedCodeInfo_Annotation_default_instance_;
class MessageOptions;
class MessageOptionsDefaultTypeInternal;
extern MessageOptionsDefaultTypeInternal _MessageOptions_default_instance_;
class MethodDescriptorProto;
class MethodDescriptorProtoDefaultTypeInternal;
extern MethodDescriptorProtoDefaultTypeInternal _MethodDescriptorProto_default_instance_;
class MethodOptions;
class MethodOptionsDefaultTypeInternal;
extern MethodOptionsDefaultTypeInternal _MethodOptions_default_instance_;
class OneofDescriptorProto;
class OneofDescriptorProtoDefaultTypeInternal;
extern OneofDescriptorProtoDefaultTypeInternal _OneofDescriptorProto_default_instance_;
class OneofOptions;
class OneofOptionsDefaultTypeInternal;
extern OneofOptionsDefaultTypeInternal _OneofOptions_default_instance_;
class ServiceDescriptorProto;
class ServiceDescriptorProtoDefaultTypeInternal;
extern ServiceDescriptorProtoDefaultTypeInternal _ServiceDescriptorProto_default_instance_;
class ServiceOptions;
class ServiceOptionsDefaultTypeInternal;
extern ServiceOptionsDefaultTypeInternal _ServiceOptions_default_instance_;
class SourceCodeInfo;
class SourceCodeInfoDefaultTypeInternal;
extern SourceCodeInfoDefaultTypeInternal _SourceCodeInfo_default_instance_;
class SourceCodeInfo_Location;
class SourceCodeInfo_LocationDefaultTypeInternal;
extern SourceCodeInfo_LocationDefaultTypeInternal _SourceCodeInfo_Location_default_instance_;
class UninterpretedOption;
class UninterpretedOptionDefaultTypeInternal;
extern UninterpretedOptionDefaultTypeInternal _UninterpretedOption_default_instance_;
class UninterpretedOption_NamePart;
class UninterpretedOption_NamePartDefaultTypeInternal;
extern UninterpretedOption_NamePartDefaultTypeInternal _UninterpretedOption_NamePart_default_instance_;
}  // namespace protobuf
}  // namespace google
namespace router {
class LookupResponse;
class LookupResponseDefaultTypeInternal;
extern LookupResponseDefaultTypeInternal _LookupResponse_default_instance_;
class RouterRequest;
class RouterRequestDefaultTypeInternal;
extern RouterRequestDefaultTypeInternal _RouterRequest_default_instance_;
class Util;
class UtilDefaultTypeInternal;
extern UtilDefaultTypeInternal _Util_default_instance_;
class UtilRequest;
class UtilRequestDefaultTypeInternal;
extern UtilRequestDefaultTypeInternal _UtilRequest_default_instance_;
class UtilResponse;
class UtilResponseDefaultTypeInternal;
extern UtilResponseDefaultTypeInternal _UtilResponse_default_instance_;
}  // namespace router

namespace router {

namespace protobuf_router_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_router_2eproto

// ===================================================================

class UtilRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:router.UtilRequest) */ {
 public:
  UtilRequest();
  virtual ~UtilRequest();

  UtilRequest(const UtilRequest& from);

  inline UtilRequest& operator=(const UtilRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UtilRequest& default_instance();

  static inline const UtilRequest* internal_default_instance() {
    return reinterpret_cast<const UtilRequest*>(
               &_UtilRequest_default_instance_);
  }

  void Swap(UtilRequest* other);

  // implements Message ----------------------------------------------

  inline UtilRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UtilRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UtilRequest& from);
  void MergeFrom(const UtilRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UtilRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool util_request = 1;
  void clear_util_request();
  static const int kUtilRequestFieldNumber = 1;
  bool util_request() const;
  void set_util_request(bool value);

  // @@protoc_insertion_point(class_scope:router.UtilRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool util_request_;
  mutable int _cached_size_;
  friend struct  protobuf_router_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RouterRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:router.RouterRequest) */ {
 public:
  RouterRequest();
  virtual ~RouterRequest();

  RouterRequest(const RouterRequest& from);

  inline RouterRequest& operator=(const RouterRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RouterRequest& default_instance();

  static inline const RouterRequest* internal_default_instance() {
    return reinterpret_cast<const RouterRequest*>(
               &_RouterRequest_default_instance_);
  }

  void Swap(RouterRequest* other);

  // implements Message ----------------------------------------------

  inline RouterRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RouterRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RouterRequest& from);
  void MergeFrom(const RouterRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RouterRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // .router.UtilRequest util_request = 4;
  bool has_util_request() const;
  void clear_util_request();
  static const int kUtilRequestFieldNumber = 4;
  const ::router::UtilRequest& util_request() const;
  ::router::UtilRequest* mutable_util_request();
  ::router::UtilRequest* release_util_request();
  void set_allocated_util_request(::router::UtilRequest* util_request);

  // uint32 operation = 3;
  void clear_operation();
  static const int kOperationFieldNumber = 3;
  ::google::protobuf::uint32 operation() const;
  void set_operation(::google::protobuf::uint32 value);

  // bool last_request = 5;
  void clear_last_request();
  static const int kLastRequestFieldNumber = 5;
  bool last_request() const;
  void set_last_request(bool value);

  // bool kill = 7;
  void clear_kill();
  static const int kKillFieldNumber = 7;
  bool kill() const;
  void set_kill(bool value);

  // uint64 resp_time = 6;
  void clear_resp_time();
  static const int kRespTimeFieldNumber = 6;
  ::google::protobuf::uint64 resp_time() const;
  void set_resp_time(::google::protobuf::uint64 value);

  // uint64 request_id = 8;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 8;
  ::google::protobuf::uint64 request_id() const;
  void set_request_id(::google::protobuf::uint64 value);

  // uint32 load = 9;
  void clear_load();
  static const int kLoadFieldNumber = 9;
  ::google::protobuf::uint32 load() const;
  void set_load(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:router.RouterRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::router::UtilRequest* util_request_;
  ::google::protobuf::uint32 operation_;
  bool last_request_;
  bool kill_;
  ::google::protobuf::uint64 resp_time_;
  ::google::protobuf::uint64 request_id_;
  ::google::protobuf::uint32 load_;
  mutable int _cached_size_;
  friend struct  protobuf_router_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Util : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:router.Util) */ {
 public:
  Util();
  virtual ~Util();

  Util(const Util& from);

  inline Util& operator=(const Util& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Util& default_instance();

  static inline const Util* internal_default_instance() {
    return reinterpret_cast<const Util*>(
               &_Util_default_instance_);
  }

  void Swap(Util* other);

  // implements Message ----------------------------------------------

  inline Util* New() const PROTOBUF_FINAL { return New(NULL); }

  Util* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Util& from);
  void MergeFrom(const Util& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Util* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 user_time = 1;
  void clear_user_time();
  static const int kUserTimeFieldNumber = 1;
  ::google::protobuf::uint64 user_time() const;
  void set_user_time(::google::protobuf::uint64 value);

  // uint64 system_time = 2;
  void clear_system_time();
  static const int kSystemTimeFieldNumber = 2;
  ::google::protobuf::uint64 system_time() const;
  void set_system_time(::google::protobuf::uint64 value);

  // uint64 io_time = 3;
  void clear_io_time();
  static const int kIoTimeFieldNumber = 3;
  ::google::protobuf::uint64 io_time() const;
  void set_io_time(::google::protobuf::uint64 value);

  // uint64 idle_time = 4;
  void clear_idle_time();
  static const int kIdleTimeFieldNumber = 4;
  ::google::protobuf::uint64 idle_time() const;
  void set_idle_time(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:router.Util)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 user_time_;
  ::google::protobuf::uint64 system_time_;
  ::google::protobuf::uint64 io_time_;
  ::google::protobuf::uint64 idle_time_;
  mutable int _cached_size_;
  friend struct  protobuf_router_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UtilResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:router.UtilResponse) */ {
 public:
  UtilResponse();
  virtual ~UtilResponse();

  UtilResponse(const UtilResponse& from);

  inline UtilResponse& operator=(const UtilResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UtilResponse& default_instance();

  static inline const UtilResponse* internal_default_instance() {
    return reinterpret_cast<const UtilResponse*>(
               &_UtilResponse_default_instance_);
  }

  void Swap(UtilResponse* other);

  // implements Message ----------------------------------------------

  inline UtilResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  UtilResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UtilResponse& from);
  void MergeFrom(const UtilResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UtilResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .router.Util lookup_srv_util = 2;
  int lookup_srv_util_size() const;
  void clear_lookup_srv_util();
  static const int kLookupSrvUtilFieldNumber = 2;
  const ::router::Util& lookup_srv_util(int index) const;
  ::router::Util* mutable_lookup_srv_util(int index);
  ::router::Util* add_lookup_srv_util();
  ::google::protobuf::RepeatedPtrField< ::router::Util >*
      mutable_lookup_srv_util();
  const ::google::protobuf::RepeatedPtrField< ::router::Util >&
      lookup_srv_util() const;

  // .router.Util router_util = 3;
  bool has_router_util() const;
  void clear_router_util();
  static const int kRouterUtilFieldNumber = 3;
  const ::router::Util& router_util() const;
  ::router::Util* mutable_router_util();
  ::router::Util* release_router_util();
  void set_allocated_router_util(::router::Util* router_util);

  // bool util_present = 1;
  void clear_util_present();
  static const int kUtilPresentFieldNumber = 1;
  bool util_present() const;
  void set_util_present(bool value);

  // @@protoc_insertion_point(class_scope:router.UtilResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::router::Util > lookup_srv_util_;
  ::router::Util* router_util_;
  bool util_present_;
  mutable int _cached_size_;
  friend struct  protobuf_router_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LookupResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:router.LookupResponse) */ {
 public:
  LookupResponse();
  virtual ~LookupResponse();

  LookupResponse(const LookupResponse& from);

  inline LookupResponse& operator=(const LookupResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LookupResponse& default_instance();

  static inline const LookupResponse* internal_default_instance() {
    return reinterpret_cast<const LookupResponse*>(
               &_LookupResponse_default_instance_);
  }

  void Swap(LookupResponse* other);

  // implements Message ----------------------------------------------

  inline LookupResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  LookupResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LookupResponse& from);
  void MergeFrom(const LookupResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LookupResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string value = 23;
  void clear_value();
  static const int kValueFieldNumber = 23;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // .router.UtilResponse util_response = 13;
  bool has_util_response() const;
  void clear_util_response();
  static const int kUtilResponseFieldNumber = 13;
  const ::router::UtilResponse& util_response() const;
  ::router::UtilResponse* mutable_util_response();
  ::router::UtilResponse* release_util_response();
  void set_allocated_util_response(::router::UtilResponse* util_response);

  // uint64 create_router_req_time = 1;
  void clear_create_router_req_time();
  static const int kCreateRouterReqTimeFieldNumber = 1;
  ::google::protobuf::uint64 create_router_req_time() const;
  void set_create_router_req_time(::google::protobuf::uint64 value);

  // uint64 unpack_router_req_time = 2;
  void clear_unpack_router_req_time();
  static const int kUnpackRouterReqTimeFieldNumber = 2;
  ::google::protobuf::uint64 unpack_router_req_time() const;
  void set_unpack_router_req_time(::google::protobuf::uint64 value);

  // uint64 update_router_util_time = 3;
  void clear_update_router_util_time();
  static const int kUpdateRouterUtilTimeFieldNumber = 3;
  ::google::protobuf::uint64 update_router_util_time() const;
  void set_update_router_util_time(::google::protobuf::uint64 value);

  // uint64 get_lookup_srv_responses_time = 5;
  void clear_get_lookup_srv_responses_time();
  static const int kGetLookupSrvResponsesTimeFieldNumber = 5;
  ::google::protobuf::uint64 get_lookup_srv_responses_time() const;
  void set_get_lookup_srv_responses_time(::google::protobuf::uint64 value);

  // uint64 create_lookup_srv_req_time = 6;
  void clear_create_lookup_srv_req_time();
  static const int kCreateLookupSrvReqTimeFieldNumber = 6;
  ::google::protobuf::uint64 create_lookup_srv_req_time() const;
  void set_create_lookup_srv_req_time(::google::protobuf::uint64 value);

  // uint64 unpack_lookup_srv_resp_time = 7;
  void clear_unpack_lookup_srv_resp_time();
  static const int kUnpackLookupSrvRespTimeFieldNumber = 7;
  ::google::protobuf::uint64 unpack_lookup_srv_resp_time() const;
  void set_unpack_lookup_srv_resp_time(::google::protobuf::uint64 value);

  // uint64 unpack_lookup_srv_req_time = 8;
  void clear_unpack_lookup_srv_req_time();
  static const int kUnpackLookupSrvReqTimeFieldNumber = 8;
  ::google::protobuf::uint64 unpack_lookup_srv_req_time() const;
  void set_unpack_lookup_srv_req_time(::google::protobuf::uint64 value);

  // uint64 lookup_srv_time = 9;
  void clear_lookup_srv_time();
  static const int kLookupSrvTimeFieldNumber = 9;
  ::google::protobuf::uint64 lookup_srv_time() const;
  void set_lookup_srv_time(::google::protobuf::uint64 value);

  // uint64 pack_lookup_srv_resp_time = 10;
  void clear_pack_lookup_srv_resp_time();
  static const int kPackLookupSrvRespTimeFieldNumber = 10;
  ::google::protobuf::uint64 pack_lookup_srv_resp_time() const;
  void set_pack_lookup_srv_resp_time(::google::protobuf::uint64 value);

  // uint64 pack_router_resp_time = 11;
  void clear_pack_router_resp_time();
  static const int kPackRouterRespTimeFieldNumber = 11;
  ::google::protobuf::uint64 pack_router_resp_time() const;
  void set_pack_router_resp_time(::google::protobuf::uint64 value);

  // uint64 resp_time = 14;
  void clear_resp_time();
  static const int kRespTimeFieldNumber = 14;
  ::google::protobuf::uint64 resp_time() const;
  void set_resp_time(::google::protobuf::uint64 value);

  // uint64 router_time = 15;
  void clear_router_time();
  static const int kRouterTimeFieldNumber = 15;
  ::google::protobuf::uint64 router_time() const;
  void set_router_time(::google::protobuf::uint64 value);

  // uint64 start_stamp = 16;
  void clear_start_stamp();
  static const int kStartStampFieldNumber = 16;
  ::google::protobuf::uint64 start_stamp() const;
  void set_start_stamp(::google::protobuf::uint64 value);

  // uint64 end_stamp = 17;
  void clear_end_stamp();
  static const int kEndStampFieldNumber = 17;
  ::google::protobuf::uint64 end_stamp() const;
  void set_end_stamp(::google::protobuf::uint64 value);

  // uint32 number_of_lookup_servers = 12;
  void clear_number_of_lookup_servers();
  static const int kNumberOfLookupServersFieldNumber = 12;
  ::google::protobuf::uint32 number_of_lookup_servers() const;
  void set_number_of_lookup_servers(::google::protobuf::uint32 value);

  // bool kill_ack = 22;
  void clear_kill_ack();
  static const int kKillAckFieldNumber = 22;
  bool kill_ack() const;
  void set_kill_ack(bool value);

  // uint64 request_id = 18;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 18;
  ::google::protobuf::uint64 request_id() const;
  void set_request_id(::google::protobuf::uint64 value);

  // uint64 num_inline = 19;
  void clear_num_inline();
  static const int kNumInlineFieldNumber = 19;
  ::google::protobuf::uint64 num_inline() const;
  void set_num_inline(::google::protobuf::uint64 value);

  // uint64 num_workers = 20;
  void clear_num_workers();
  static const int kNumWorkersFieldNumber = 20;
  ::google::protobuf::uint64 num_workers() const;
  void set_num_workers(::google::protobuf::uint64 value);

  // uint64 num_resp = 21;
  void clear_num_resp();
  static const int kNumRespFieldNumber = 21;
  ::google::protobuf::uint64 num_resp() const;
  void set_num_resp(::google::protobuf::uint64 value);

  // uint64 merge_time = 24;
  void clear_merge_time();
  static const int kMergeTimeFieldNumber = 24;
  ::google::protobuf::uint64 merge_time() const;
  void set_merge_time(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:router.LookupResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::router::UtilResponse* util_response_;
  ::google::protobuf::uint64 create_router_req_time_;
  ::google::protobuf::uint64 unpack_router_req_time_;
  ::google::protobuf::uint64 update_router_util_time_;
  ::google::protobuf::uint64 get_lookup_srv_responses_time_;
  ::google::protobuf::uint64 create_lookup_srv_req_time_;
  ::google::protobuf::uint64 unpack_lookup_srv_resp_time_;
  ::google::protobuf::uint64 unpack_lookup_srv_req_time_;
  ::google::protobuf::uint64 lookup_srv_time_;
  ::google::protobuf::uint64 pack_lookup_srv_resp_time_;
  ::google::protobuf::uint64 pack_router_resp_time_;
  ::google::protobuf::uint64 resp_time_;
  ::google::protobuf::uint64 router_time_;
  ::google::protobuf::uint64 start_stamp_;
  ::google::protobuf::uint64 end_stamp_;
  ::google::protobuf::uint32 number_of_lookup_servers_;
  bool kill_ack_;
  ::google::protobuf::uint64 request_id_;
  ::google::protobuf::uint64 num_inline_;
  ::google::protobuf::uint64 num_workers_;
  ::google::protobuf::uint64 num_resp_;
  ::google::protobuf::uint64 merge_time_;
  mutable int _cached_size_;
  friend struct  protobuf_router_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UtilRequest

// bool util_request = 1;
inline void UtilRequest::clear_util_request() {
  util_request_ = false;
}
inline bool UtilRequest::util_request() const {
  // @@protoc_insertion_point(field_get:router.UtilRequest.util_request)
  return util_request_;
}
inline void UtilRequest::set_util_request(bool value) {
  
  util_request_ = value;
  // @@protoc_insertion_point(field_set:router.UtilRequest.util_request)
}

// -------------------------------------------------------------------

// RouterRequest

// string key = 1;
inline void RouterRequest::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RouterRequest::key() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.key)
  return key_.GetNoArena();
}
inline void RouterRequest::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:router.RouterRequest.key)
}
#if LANG_CXX11
inline void RouterRequest::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:router.RouterRequest.key)
}
#endif
inline void RouterRequest::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:router.RouterRequest.key)
}
inline void RouterRequest::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:router.RouterRequest.key)
}
inline ::std::string* RouterRequest::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:router.RouterRequest.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RouterRequest::release_key() {
  // @@protoc_insertion_point(field_release:router.RouterRequest.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RouterRequest::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:router.RouterRequest.key)
}

// string value = 2;
inline void RouterRequest::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RouterRequest::value() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.value)
  return value_.GetNoArena();
}
inline void RouterRequest::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:router.RouterRequest.value)
}
#if LANG_CXX11
inline void RouterRequest::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:router.RouterRequest.value)
}
#endif
inline void RouterRequest::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:router.RouterRequest.value)
}
inline void RouterRequest::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:router.RouterRequest.value)
}
inline ::std::string* RouterRequest::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:router.RouterRequest.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RouterRequest::release_value() {
  // @@protoc_insertion_point(field_release:router.RouterRequest.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RouterRequest::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:router.RouterRequest.value)
}

// uint32 operation = 3;
inline void RouterRequest::clear_operation() {
  operation_ = 0u;
}
inline ::google::protobuf::uint32 RouterRequest::operation() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.operation)
  return operation_;
}
inline void RouterRequest::set_operation(::google::protobuf::uint32 value) {
  
  operation_ = value;
  // @@protoc_insertion_point(field_set:router.RouterRequest.operation)
}

// .router.UtilRequest util_request = 4;
inline bool RouterRequest::has_util_request() const {
  return this != internal_default_instance() && util_request_ != NULL;
}
inline void RouterRequest::clear_util_request() {
  if (GetArenaNoVirtual() == NULL && util_request_ != NULL) delete util_request_;
  util_request_ = NULL;
}
inline const ::router::UtilRequest& RouterRequest::util_request() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.util_request)
  return util_request_ != NULL ? *util_request_
                         : *::router::UtilRequest::internal_default_instance();
}
inline ::router::UtilRequest* RouterRequest::mutable_util_request() {
  
  if (util_request_ == NULL) {
    util_request_ = new ::router::UtilRequest;
  }
  // @@protoc_insertion_point(field_mutable:router.RouterRequest.util_request)
  return util_request_;
}
inline ::router::UtilRequest* RouterRequest::release_util_request() {
  // @@protoc_insertion_point(field_release:router.RouterRequest.util_request)
  
  ::router::UtilRequest* temp = util_request_;
  util_request_ = NULL;
  return temp;
}
inline void RouterRequest::set_allocated_util_request(::router::UtilRequest* util_request) {
  delete util_request_;
  util_request_ = util_request;
  if (util_request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:router.RouterRequest.util_request)
}

// bool last_request = 5;
inline void RouterRequest::clear_last_request() {
  last_request_ = false;
}
inline bool RouterRequest::last_request() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.last_request)
  return last_request_;
}
inline void RouterRequest::set_last_request(bool value) {
  
  last_request_ = value;
  // @@protoc_insertion_point(field_set:router.RouterRequest.last_request)
}

// uint64 resp_time = 6;
inline void RouterRequest::clear_resp_time() {
  resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RouterRequest::resp_time() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.resp_time)
  return resp_time_;
}
inline void RouterRequest::set_resp_time(::google::protobuf::uint64 value) {
  
  resp_time_ = value;
  // @@protoc_insertion_point(field_set:router.RouterRequest.resp_time)
}

// bool kill = 7;
inline void RouterRequest::clear_kill() {
  kill_ = false;
}
inline bool RouterRequest::kill() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.kill)
  return kill_;
}
inline void RouterRequest::set_kill(bool value) {
  
  kill_ = value;
  // @@protoc_insertion_point(field_set:router.RouterRequest.kill)
}

// uint64 request_id = 8;
inline void RouterRequest::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RouterRequest::request_id() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.request_id)
  return request_id_;
}
inline void RouterRequest::set_request_id(::google::protobuf::uint64 value) {
  
  request_id_ = value;
  // @@protoc_insertion_point(field_set:router.RouterRequest.request_id)
}

// uint32 load = 9;
inline void RouterRequest::clear_load() {
  load_ = 0u;
}
inline ::google::protobuf::uint32 RouterRequest::load() const {
  // @@protoc_insertion_point(field_get:router.RouterRequest.load)
  return load_;
}
inline void RouterRequest::set_load(::google::protobuf::uint32 value) {
  
  load_ = value;
  // @@protoc_insertion_point(field_set:router.RouterRequest.load)
}

// -------------------------------------------------------------------

// Util

// uint64 user_time = 1;
inline void Util::clear_user_time() {
  user_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Util::user_time() const {
  // @@protoc_insertion_point(field_get:router.Util.user_time)
  return user_time_;
}
inline void Util::set_user_time(::google::protobuf::uint64 value) {
  
  user_time_ = value;
  // @@protoc_insertion_point(field_set:router.Util.user_time)
}

// uint64 system_time = 2;
inline void Util::clear_system_time() {
  system_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Util::system_time() const {
  // @@protoc_insertion_point(field_get:router.Util.system_time)
  return system_time_;
}
inline void Util::set_system_time(::google::protobuf::uint64 value) {
  
  system_time_ = value;
  // @@protoc_insertion_point(field_set:router.Util.system_time)
}

// uint64 io_time = 3;
inline void Util::clear_io_time() {
  io_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Util::io_time() const {
  // @@protoc_insertion_point(field_get:router.Util.io_time)
  return io_time_;
}
inline void Util::set_io_time(::google::protobuf::uint64 value) {
  
  io_time_ = value;
  // @@protoc_insertion_point(field_set:router.Util.io_time)
}

// uint64 idle_time = 4;
inline void Util::clear_idle_time() {
  idle_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Util::idle_time() const {
  // @@protoc_insertion_point(field_get:router.Util.idle_time)
  return idle_time_;
}
inline void Util::set_idle_time(::google::protobuf::uint64 value) {
  
  idle_time_ = value;
  // @@protoc_insertion_point(field_set:router.Util.idle_time)
}

// -------------------------------------------------------------------

// UtilResponse

// bool util_present = 1;
inline void UtilResponse::clear_util_present() {
  util_present_ = false;
}
inline bool UtilResponse::util_present() const {
  // @@protoc_insertion_point(field_get:router.UtilResponse.util_present)
  return util_present_;
}
inline void UtilResponse::set_util_present(bool value) {
  
  util_present_ = value;
  // @@protoc_insertion_point(field_set:router.UtilResponse.util_present)
}

// repeated .router.Util lookup_srv_util = 2;
inline int UtilResponse::lookup_srv_util_size() const {
  return lookup_srv_util_.size();
}
inline void UtilResponse::clear_lookup_srv_util() {
  lookup_srv_util_.Clear();
}
inline const ::router::Util& UtilResponse::lookup_srv_util(int index) const {
  // @@protoc_insertion_point(field_get:router.UtilResponse.lookup_srv_util)
  return lookup_srv_util_.Get(index);
}
inline ::router::Util* UtilResponse::mutable_lookup_srv_util(int index) {
  // @@protoc_insertion_point(field_mutable:router.UtilResponse.lookup_srv_util)
  return lookup_srv_util_.Mutable(index);
}
inline ::router::Util* UtilResponse::add_lookup_srv_util() {
  // @@protoc_insertion_point(field_add:router.UtilResponse.lookup_srv_util)
  return lookup_srv_util_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::router::Util >*
UtilResponse::mutable_lookup_srv_util() {
  // @@protoc_insertion_point(field_mutable_list:router.UtilResponse.lookup_srv_util)
  return &lookup_srv_util_;
}
inline const ::google::protobuf::RepeatedPtrField< ::router::Util >&
UtilResponse::lookup_srv_util() const {
  // @@protoc_insertion_point(field_list:router.UtilResponse.lookup_srv_util)
  return lookup_srv_util_;
}

// .router.Util router_util = 3;
inline bool UtilResponse::has_router_util() const {
  return this != internal_default_instance() && router_util_ != NULL;
}
inline void UtilResponse::clear_router_util() {
  if (GetArenaNoVirtual() == NULL && router_util_ != NULL) delete router_util_;
  router_util_ = NULL;
}
inline const ::router::Util& UtilResponse::router_util() const {
  // @@protoc_insertion_point(field_get:router.UtilResponse.router_util)
  return router_util_ != NULL ? *router_util_
                         : *::router::Util::internal_default_instance();
}
inline ::router::Util* UtilResponse::mutable_router_util() {
  
  if (router_util_ == NULL) {
    router_util_ = new ::router::Util;
  }
  // @@protoc_insertion_point(field_mutable:router.UtilResponse.router_util)
  return router_util_;
}
inline ::router::Util* UtilResponse::release_router_util() {
  // @@protoc_insertion_point(field_release:router.UtilResponse.router_util)
  
  ::router::Util* temp = router_util_;
  router_util_ = NULL;
  return temp;
}
inline void UtilResponse::set_allocated_router_util(::router::Util* router_util) {
  delete router_util_;
  router_util_ = router_util;
  if (router_util) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:router.UtilResponse.router_util)
}

// -------------------------------------------------------------------

// LookupResponse

// uint64 create_router_req_time = 1;
inline void LookupResponse::clear_create_router_req_time() {
  create_router_req_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::create_router_req_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.create_router_req_time)
  return create_router_req_time_;
}
inline void LookupResponse::set_create_router_req_time(::google::protobuf::uint64 value) {
  
  create_router_req_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.create_router_req_time)
}

// uint64 unpack_router_req_time = 2;
inline void LookupResponse::clear_unpack_router_req_time() {
  unpack_router_req_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::unpack_router_req_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.unpack_router_req_time)
  return unpack_router_req_time_;
}
inline void LookupResponse::set_unpack_router_req_time(::google::protobuf::uint64 value) {
  
  unpack_router_req_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.unpack_router_req_time)
}

// uint64 update_router_util_time = 3;
inline void LookupResponse::clear_update_router_util_time() {
  update_router_util_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::update_router_util_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.update_router_util_time)
  return update_router_util_time_;
}
inline void LookupResponse::set_update_router_util_time(::google::protobuf::uint64 value) {
  
  update_router_util_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.update_router_util_time)
}

// uint64 get_lookup_srv_responses_time = 5;
inline void LookupResponse::clear_get_lookup_srv_responses_time() {
  get_lookup_srv_responses_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::get_lookup_srv_responses_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.get_lookup_srv_responses_time)
  return get_lookup_srv_responses_time_;
}
inline void LookupResponse::set_get_lookup_srv_responses_time(::google::protobuf::uint64 value) {
  
  get_lookup_srv_responses_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.get_lookup_srv_responses_time)
}

// uint64 create_lookup_srv_req_time = 6;
inline void LookupResponse::clear_create_lookup_srv_req_time() {
  create_lookup_srv_req_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::create_lookup_srv_req_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.create_lookup_srv_req_time)
  return create_lookup_srv_req_time_;
}
inline void LookupResponse::set_create_lookup_srv_req_time(::google::protobuf::uint64 value) {
  
  create_lookup_srv_req_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.create_lookup_srv_req_time)
}

// uint64 unpack_lookup_srv_resp_time = 7;
inline void LookupResponse::clear_unpack_lookup_srv_resp_time() {
  unpack_lookup_srv_resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::unpack_lookup_srv_resp_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.unpack_lookup_srv_resp_time)
  return unpack_lookup_srv_resp_time_;
}
inline void LookupResponse::set_unpack_lookup_srv_resp_time(::google::protobuf::uint64 value) {
  
  unpack_lookup_srv_resp_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.unpack_lookup_srv_resp_time)
}

// uint64 unpack_lookup_srv_req_time = 8;
inline void LookupResponse::clear_unpack_lookup_srv_req_time() {
  unpack_lookup_srv_req_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::unpack_lookup_srv_req_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.unpack_lookup_srv_req_time)
  return unpack_lookup_srv_req_time_;
}
inline void LookupResponse::set_unpack_lookup_srv_req_time(::google::protobuf::uint64 value) {
  
  unpack_lookup_srv_req_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.unpack_lookup_srv_req_time)
}

// uint64 lookup_srv_time = 9;
inline void LookupResponse::clear_lookup_srv_time() {
  lookup_srv_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::lookup_srv_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.lookup_srv_time)
  return lookup_srv_time_;
}
inline void LookupResponse::set_lookup_srv_time(::google::protobuf::uint64 value) {
  
  lookup_srv_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.lookup_srv_time)
}

// uint64 pack_lookup_srv_resp_time = 10;
inline void LookupResponse::clear_pack_lookup_srv_resp_time() {
  pack_lookup_srv_resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::pack_lookup_srv_resp_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.pack_lookup_srv_resp_time)
  return pack_lookup_srv_resp_time_;
}
inline void LookupResponse::set_pack_lookup_srv_resp_time(::google::protobuf::uint64 value) {
  
  pack_lookup_srv_resp_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.pack_lookup_srv_resp_time)
}

// uint64 pack_router_resp_time = 11;
inline void LookupResponse::clear_pack_router_resp_time() {
  pack_router_resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::pack_router_resp_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.pack_router_resp_time)
  return pack_router_resp_time_;
}
inline void LookupResponse::set_pack_router_resp_time(::google::protobuf::uint64 value) {
  
  pack_router_resp_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.pack_router_resp_time)
}

// uint32 number_of_lookup_servers = 12;
inline void LookupResponse::clear_number_of_lookup_servers() {
  number_of_lookup_servers_ = 0u;
}
inline ::google::protobuf::uint32 LookupResponse::number_of_lookup_servers() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.number_of_lookup_servers)
  return number_of_lookup_servers_;
}
inline void LookupResponse::set_number_of_lookup_servers(::google::protobuf::uint32 value) {
  
  number_of_lookup_servers_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.number_of_lookup_servers)
}

// .router.UtilResponse util_response = 13;
inline bool LookupResponse::has_util_response() const {
  return this != internal_default_instance() && util_response_ != NULL;
}
inline void LookupResponse::clear_util_response() {
  if (GetArenaNoVirtual() == NULL && util_response_ != NULL) delete util_response_;
  util_response_ = NULL;
}
inline const ::router::UtilResponse& LookupResponse::util_response() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.util_response)
  return util_response_ != NULL ? *util_response_
                         : *::router::UtilResponse::internal_default_instance();
}
inline ::router::UtilResponse* LookupResponse::mutable_util_response() {
  
  if (util_response_ == NULL) {
    util_response_ = new ::router::UtilResponse;
  }
  // @@protoc_insertion_point(field_mutable:router.LookupResponse.util_response)
  return util_response_;
}
inline ::router::UtilResponse* LookupResponse::release_util_response() {
  // @@protoc_insertion_point(field_release:router.LookupResponse.util_response)
  
  ::router::UtilResponse* temp = util_response_;
  util_response_ = NULL;
  return temp;
}
inline void LookupResponse::set_allocated_util_response(::router::UtilResponse* util_response) {
  delete util_response_;
  util_response_ = util_response;
  if (util_response) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:router.LookupResponse.util_response)
}

// uint64 resp_time = 14;
inline void LookupResponse::clear_resp_time() {
  resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::resp_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.resp_time)
  return resp_time_;
}
inline void LookupResponse::set_resp_time(::google::protobuf::uint64 value) {
  
  resp_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.resp_time)
}

// uint64 router_time = 15;
inline void LookupResponse::clear_router_time() {
  router_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::router_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.router_time)
  return router_time_;
}
inline void LookupResponse::set_router_time(::google::protobuf::uint64 value) {
  
  router_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.router_time)
}

// uint64 start_stamp = 16;
inline void LookupResponse::clear_start_stamp() {
  start_stamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::start_stamp() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.start_stamp)
  return start_stamp_;
}
inline void LookupResponse::set_start_stamp(::google::protobuf::uint64 value) {
  
  start_stamp_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.start_stamp)
}

// uint64 end_stamp = 17;
inline void LookupResponse::clear_end_stamp() {
  end_stamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::end_stamp() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.end_stamp)
  return end_stamp_;
}
inline void LookupResponse::set_end_stamp(::google::protobuf::uint64 value) {
  
  end_stamp_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.end_stamp)
}

// uint64 request_id = 18;
inline void LookupResponse::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::request_id() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.request_id)
  return request_id_;
}
inline void LookupResponse::set_request_id(::google::protobuf::uint64 value) {
  
  request_id_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.request_id)
}

// uint64 num_inline = 19;
inline void LookupResponse::clear_num_inline() {
  num_inline_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::num_inline() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.num_inline)
  return num_inline_;
}
inline void LookupResponse::set_num_inline(::google::protobuf::uint64 value) {
  
  num_inline_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.num_inline)
}

// uint64 num_workers = 20;
inline void LookupResponse::clear_num_workers() {
  num_workers_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::num_workers() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.num_workers)
  return num_workers_;
}
inline void LookupResponse::set_num_workers(::google::protobuf::uint64 value) {
  
  num_workers_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.num_workers)
}

// uint64 num_resp = 21;
inline void LookupResponse::clear_num_resp() {
  num_resp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::num_resp() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.num_resp)
  return num_resp_;
}
inline void LookupResponse::set_num_resp(::google::protobuf::uint64 value) {
  
  num_resp_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.num_resp)
}

// bool kill_ack = 22;
inline void LookupResponse::clear_kill_ack() {
  kill_ack_ = false;
}
inline bool LookupResponse::kill_ack() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.kill_ack)
  return kill_ack_;
}
inline void LookupResponse::set_kill_ack(bool value) {
  
  kill_ack_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.kill_ack)
}

// string value = 23;
inline void LookupResponse::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LookupResponse::value() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.value)
  return value_.GetNoArena();
}
inline void LookupResponse::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:router.LookupResponse.value)
}
#if LANG_CXX11
inline void LookupResponse::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:router.LookupResponse.value)
}
#endif
inline void LookupResponse::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:router.LookupResponse.value)
}
inline void LookupResponse::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:router.LookupResponse.value)
}
inline ::std::string* LookupResponse::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:router.LookupResponse.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LookupResponse::release_value() {
  // @@protoc_insertion_point(field_release:router.LookupResponse.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LookupResponse::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:router.LookupResponse.value)
}

// uint64 merge_time = 24;
inline void LookupResponse::clear_merge_time() {
  merge_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LookupResponse::merge_time() const {
  // @@protoc_insertion_point(field_get:router.LookupResponse.merge_time)
  return merge_time_;
}
inline void LookupResponse::set_merge_time(::google::protobuf::uint64 value) {
  
  merge_time_ = value;
  // @@protoc_insertion_point(field_set:router.LookupResponse.merge_time)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace router

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_router_2eproto__INCLUDED
