// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: router.proto
#ifndef GRPC_router_2eproto__INCLUDED
#define GRPC_router_2eproto__INCLUDED

#include "router.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace router {

class RouterService final {
 public:
  static constexpr char const* service_full_name() {
    return "router.RouterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Defining service between load generator and index.
    // Input: Queries, number of nearest neighbors to compute.
    // Output: K-nn
    virtual ::grpc::Status Router(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::router::LookupResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::router::LookupResponse>> AsyncRouter(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::router::LookupResponse>>(AsyncRouterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::router::LookupResponse>> PrepareAsyncRouter(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::router::LookupResponse>>(PrepareAsyncRouterRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::router::LookupResponse>* AsyncRouterRaw(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::router::LookupResponse>* PrepareAsyncRouterRaw(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Router(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::router::LookupResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::router::LookupResponse>> AsyncRouter(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::router::LookupResponse>>(AsyncRouterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::router::LookupResponse>> PrepareAsyncRouter(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::router::LookupResponse>>(PrepareAsyncRouterRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::router::LookupResponse>* AsyncRouterRaw(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::router::LookupResponse>* PrepareAsyncRouterRaw(::grpc::ClientContext* context, const ::router::RouterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Router_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Defining service between load generator and index.
    // Input: Queries, number of nearest neighbors to compute.
    // Output: K-nn
    virtual ::grpc::Status Router(::grpc::ServerContext* context, const ::router::RouterRequest* request, ::router::LookupResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Router : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Router() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Router() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Router(::grpc::ServerContext* context, const ::router::RouterRequest* request, ::router::LookupResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRouter(::grpc::ServerContext* context, ::router::RouterRequest* request, ::grpc::ServerAsyncResponseWriter< ::router::LookupResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Router<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Router : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Router() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Router() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Router(::grpc::ServerContext* context, const ::router::RouterRequest* request, ::router::LookupResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Router : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Router() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::router::RouterRequest, ::router::LookupResponse>(std::bind(&WithStreamedUnaryMethod_Router<BaseClass>::StreamedRouter, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Router() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Router(::grpc::ServerContext* context, const ::router::RouterRequest* request, ::router::LookupResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRouter(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::router::RouterRequest,::router::LookupResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Router<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Router<Service > StreamedService;
};

}  // namespace router


#endif  // GRPC_router_2eproto__INCLUDED
