// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: intersection.proto

#ifndef PROTOBUF_intersection_2eproto__INCLUDED
#define PROTOBUF_intersection_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace intersection {
class IntersectionRequest;
class IntersectionRequestDefaultTypeInternal;
extern IntersectionRequestDefaultTypeInternal _IntersectionRequest_default_instance_;
class IntersectionResponse;
class IntersectionResponseDefaultTypeInternal;
extern IntersectionResponseDefaultTypeInternal _IntersectionResponse_default_instance_;
class TimingDataInMicro;
class TimingDataInMicroDefaultTypeInternal;
extern TimingDataInMicroDefaultTypeInternal _TimingDataInMicro_default_instance_;
class UtilRequest;
class UtilRequestDefaultTypeInternal;
extern UtilRequestDefaultTypeInternal _UtilRequest_default_instance_;
class UtilResponse;
class UtilResponseDefaultTypeInternal;
extern UtilResponseDefaultTypeInternal _UtilResponse_default_instance_;
}  // namespace intersection

namespace intersection {

namespace protobuf_intersection_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_intersection_2eproto

// ===================================================================

class UtilRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:intersection.UtilRequest) */ {
 public:
  UtilRequest();
  virtual ~UtilRequest();

  UtilRequest(const UtilRequest& from);

  inline UtilRequest& operator=(const UtilRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UtilRequest& default_instance();

  static inline const UtilRequest* internal_default_instance() {
    return reinterpret_cast<const UtilRequest*>(
               &_UtilRequest_default_instance_);
  }

  void Swap(UtilRequest* other);

  // implements Message ----------------------------------------------

  inline UtilRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UtilRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UtilRequest& from);
  void MergeFrom(const UtilRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UtilRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool util_request = 1;
  void clear_util_request();
  static const int kUtilRequestFieldNumber = 1;
  bool util_request() const;
  void set_util_request(bool value);

  // @@protoc_insertion_point(class_scope:intersection.UtilRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool util_request_;
  mutable int _cached_size_;
  friend struct  protobuf_intersection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class IntersectionRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:intersection.IntersectionRequest) */ {
 public:
  IntersectionRequest();
  virtual ~IntersectionRequest();

  IntersectionRequest(const IntersectionRequest& from);

  inline IntersectionRequest& operator=(const IntersectionRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IntersectionRequest& default_instance();

  static inline const IntersectionRequest* internal_default_instance() {
    return reinterpret_cast<const IntersectionRequest*>(
               &_IntersectionRequest_default_instance_);
  }

  void Swap(IntersectionRequest* other);

  // implements Message ----------------------------------------------

  inline IntersectionRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  IntersectionRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const IntersectionRequest& from);
  void MergeFrom(const IntersectionRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(IntersectionRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 word_ids = 1;
  int word_ids_size() const;
  void clear_word_ids();
  static const int kWordIdsFieldNumber = 1;
  ::google::protobuf::uint64 word_ids(int index) const;
  void set_word_ids(int index, ::google::protobuf::uint64 value);
  void add_word_ids(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      word_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_word_ids();

  // .intersection.UtilRequest util_request = 4;
  bool has_util_request() const;
  void clear_util_request();
  static const int kUtilRequestFieldNumber = 4;
  const ::intersection::UtilRequest& util_request() const;
  ::intersection::UtilRequest* mutable_util_request();
  ::intersection::UtilRequest* release_util_request();
  void set_allocated_util_request(::intersection::UtilRequest* util_request);

  // uint32 intersection_server_id = 2;
  void clear_intersection_server_id();
  static const int kIntersectionServerIdFieldNumber = 2;
  ::google::protobuf::uint32 intersection_server_id() const;
  void set_intersection_server_id(::google::protobuf::uint32 value);

  // uint32 shard_size = 3;
  void clear_shard_size();
  static const int kShardSizeFieldNumber = 3;
  ::google::protobuf::uint32 shard_size() const;
  void set_shard_size(::google::protobuf::uint32 value);

  // uint64 request_id = 5;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 5;
  ::google::protobuf::uint64 request_id() const;
  void set_request_id(::google::protobuf::uint64 value);

  // uint64 index_view = 6;
  void clear_index_view();
  static const int kIndexViewFieldNumber = 6;
  ::google::protobuf::uint64 index_view() const;
  void set_index_view(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:intersection.IntersectionRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > word_ids_;
  mutable int _word_ids_cached_byte_size_;
  ::intersection::UtilRequest* util_request_;
  ::google::protobuf::uint32 intersection_server_id_;
  ::google::protobuf::uint32 shard_size_;
  ::google::protobuf::uint64 request_id_;
  ::google::protobuf::uint64 index_view_;
  mutable int _cached_size_;
  friend struct  protobuf_intersection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TimingDataInMicro : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:intersection.TimingDataInMicro) */ {
 public:
  TimingDataInMicro();
  virtual ~TimingDataInMicro();

  TimingDataInMicro(const TimingDataInMicro& from);

  inline TimingDataInMicro& operator=(const TimingDataInMicro& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TimingDataInMicro& default_instance();

  static inline const TimingDataInMicro* internal_default_instance() {
    return reinterpret_cast<const TimingDataInMicro*>(
               &_TimingDataInMicro_default_instance_);
  }

  void Swap(TimingDataInMicro* other);

  // implements Message ----------------------------------------------

  inline TimingDataInMicro* New() const PROTOBUF_FINAL { return New(NULL); }

  TimingDataInMicro* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TimingDataInMicro& from);
  void MergeFrom(const TimingDataInMicro& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TimingDataInMicro* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 unpack_intersection_srv_req_time_in_micro = 1;
  void clear_unpack_intersection_srv_req_time_in_micro();
  static const int kUnpackIntersectionSrvReqTimeInMicroFieldNumber = 1;
  ::google::protobuf::uint64 unpack_intersection_srv_req_time_in_micro() const;
  void set_unpack_intersection_srv_req_time_in_micro(::google::protobuf::uint64 value);

  // uint64 calculate_intersection_time_in_micro = 2;
  void clear_calculate_intersection_time_in_micro();
  static const int kCalculateIntersectionTimeInMicroFieldNumber = 2;
  ::google::protobuf::uint64 calculate_intersection_time_in_micro() const;
  void set_calculate_intersection_time_in_micro(::google::protobuf::uint64 value);

  // uint64 pack_intersection_srv_resp_time_in_micro = 3;
  void clear_pack_intersection_srv_resp_time_in_micro();
  static const int kPackIntersectionSrvRespTimeInMicroFieldNumber = 3;
  ::google::protobuf::uint64 pack_intersection_srv_resp_time_in_micro() const;
  void set_pack_intersection_srv_resp_time_in_micro(::google::protobuf::uint64 value);

  // float cpu_util = 4;
  void clear_cpu_util();
  static const int kCpuUtilFieldNumber = 4;
  float cpu_util() const;
  void set_cpu_util(float value);

  // @@protoc_insertion_point(class_scope:intersection.TimingDataInMicro)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 unpack_intersection_srv_req_time_in_micro_;
  ::google::protobuf::uint64 calculate_intersection_time_in_micro_;
  ::google::protobuf::uint64 pack_intersection_srv_resp_time_in_micro_;
  float cpu_util_;
  mutable int _cached_size_;
  friend struct  protobuf_intersection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UtilResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:intersection.UtilResponse) */ {
 public:
  UtilResponse();
  virtual ~UtilResponse();

  UtilResponse(const UtilResponse& from);

  inline UtilResponse& operator=(const UtilResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UtilResponse& default_instance();

  static inline const UtilResponse* internal_default_instance() {
    return reinterpret_cast<const UtilResponse*>(
               &_UtilResponse_default_instance_);
  }

  void Swap(UtilResponse* other);

  // implements Message ----------------------------------------------

  inline UtilResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  UtilResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UtilResponse& from);
  void MergeFrom(const UtilResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UtilResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 user_time = 2;
  void clear_user_time();
  static const int kUserTimeFieldNumber = 2;
  ::google::protobuf::uint64 user_time() const;
  void set_user_time(::google::protobuf::uint64 value);

  // uint64 system_time = 3;
  void clear_system_time();
  static const int kSystemTimeFieldNumber = 3;
  ::google::protobuf::uint64 system_time() const;
  void set_system_time(::google::protobuf::uint64 value);

  // uint64 io_time = 4;
  void clear_io_time();
  static const int kIoTimeFieldNumber = 4;
  ::google::protobuf::uint64 io_time() const;
  void set_io_time(::google::protobuf::uint64 value);

  // uint64 idle_time = 5;
  void clear_idle_time();
  static const int kIdleTimeFieldNumber = 5;
  ::google::protobuf::uint64 idle_time() const;
  void set_idle_time(::google::protobuf::uint64 value);

  // bool util_present = 1;
  void clear_util_present();
  static const int kUtilPresentFieldNumber = 1;
  bool util_present() const;
  void set_util_present(bool value);

  // @@protoc_insertion_point(class_scope:intersection.UtilResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 user_time_;
  ::google::protobuf::uint64 system_time_;
  ::google::protobuf::uint64 io_time_;
  ::google::protobuf::uint64 idle_time_;
  bool util_present_;
  mutable int _cached_size_;
  friend struct  protobuf_intersection_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class IntersectionResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:intersection.IntersectionResponse) */ {
 public:
  IntersectionResponse();
  virtual ~IntersectionResponse();

  IntersectionResponse(const IntersectionResponse& from);

  inline IntersectionResponse& operator=(const IntersectionResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IntersectionResponse& default_instance();

  static inline const IntersectionResponse* internal_default_instance() {
    return reinterpret_cast<const IntersectionResponse*>(
               &_IntersectionResponse_default_instance_);
  }

  void Swap(IntersectionResponse* other);

  // implements Message ----------------------------------------------

  inline IntersectionResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  IntersectionResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const IntersectionResponse& from);
  void MergeFrom(const IntersectionResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(IntersectionResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 doc_ids = 1;
  int doc_ids_size() const;
  void clear_doc_ids();
  static const int kDocIdsFieldNumber = 1;
  ::google::protobuf::uint64 doc_ids(int index) const;
  void set_doc_ids(int index, ::google::protobuf::uint64 value);
  void add_doc_ids(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      doc_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_doc_ids();

  // .intersection.TimingDataInMicro timing_data_in_micro = 2;
  bool has_timing_data_in_micro() const;
  void clear_timing_data_in_micro();
  static const int kTimingDataInMicroFieldNumber = 2;
  const ::intersection::TimingDataInMicro& timing_data_in_micro() const;
  ::intersection::TimingDataInMicro* mutable_timing_data_in_micro();
  ::intersection::TimingDataInMicro* release_timing_data_in_micro();
  void set_allocated_timing_data_in_micro(::intersection::TimingDataInMicro* timing_data_in_micro);

  // .intersection.UtilResponse util_response = 3;
  bool has_util_response() const;
  void clear_util_response();
  static const int kUtilResponseFieldNumber = 3;
  const ::intersection::UtilResponse& util_response() const;
  ::intersection::UtilResponse* mutable_util_response();
  ::intersection::UtilResponse* release_util_response();
  void set_allocated_util_response(::intersection::UtilResponse* util_response);

  // uint64 request_id = 4;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 4;
  ::google::protobuf::uint64 request_id() const;
  void set_request_id(::google::protobuf::uint64 value);

  // uint64 recv_stamp = 5;
  void clear_recv_stamp();
  static const int kRecvStampFieldNumber = 5;
  ::google::protobuf::uint64 recv_stamp() const;
  void set_recv_stamp(::google::protobuf::uint64 value);

  // uint64 send_stamp = 6;
  void clear_send_stamp();
  static const int kSendStampFieldNumber = 6;
  ::google::protobuf::uint64 send_stamp() const;
  void set_send_stamp(::google::protobuf::uint64 value);

  // uint64 index_view = 7;
  void clear_index_view();
  static const int kIndexViewFieldNumber = 7;
  ::google::protobuf::uint64 index_view() const;
  void set_index_view(::google::protobuf::uint64 value);

  // uint32 request_server_id = 8;
  void clear_request_server_id();
  static const int kRequestServerIdFieldNumber = 8;
  ::google::protobuf::uint32 request_server_id() const;
  void set_request_server_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:intersection.IntersectionResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > doc_ids_;
  mutable int _doc_ids_cached_byte_size_;
  ::intersection::TimingDataInMicro* timing_data_in_micro_;
  ::intersection::UtilResponse* util_response_;
  ::google::protobuf::uint64 request_id_;
  ::google::protobuf::uint64 recv_stamp_;
  ::google::protobuf::uint64 send_stamp_;
  ::google::protobuf::uint64 index_view_;
  ::google::protobuf::uint32 request_server_id_;
  mutable int _cached_size_;
  friend struct  protobuf_intersection_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UtilRequest

// bool util_request = 1;
inline void UtilRequest::clear_util_request() {
  util_request_ = false;
}
inline bool UtilRequest::util_request() const {
  // @@protoc_insertion_point(field_get:intersection.UtilRequest.util_request)
  return util_request_;
}
inline void UtilRequest::set_util_request(bool value) {
  
  util_request_ = value;
  // @@protoc_insertion_point(field_set:intersection.UtilRequest.util_request)
}

// -------------------------------------------------------------------

// IntersectionRequest

// repeated uint64 word_ids = 1;
inline int IntersectionRequest::word_ids_size() const {
  return word_ids_.size();
}
inline void IntersectionRequest::clear_word_ids() {
  word_ids_.Clear();
}
inline ::google::protobuf::uint64 IntersectionRequest::word_ids(int index) const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionRequest.word_ids)
  return word_ids_.Get(index);
}
inline void IntersectionRequest::set_word_ids(int index, ::google::protobuf::uint64 value) {
  word_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:intersection.IntersectionRequest.word_ids)
}
inline void IntersectionRequest::add_word_ids(::google::protobuf::uint64 value) {
  word_ids_.Add(value);
  // @@protoc_insertion_point(field_add:intersection.IntersectionRequest.word_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
IntersectionRequest::word_ids() const {
  // @@protoc_insertion_point(field_list:intersection.IntersectionRequest.word_ids)
  return word_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
IntersectionRequest::mutable_word_ids() {
  // @@protoc_insertion_point(field_mutable_list:intersection.IntersectionRequest.word_ids)
  return &word_ids_;
}

// uint32 intersection_server_id = 2;
inline void IntersectionRequest::clear_intersection_server_id() {
  intersection_server_id_ = 0u;
}
inline ::google::protobuf::uint32 IntersectionRequest::intersection_server_id() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionRequest.intersection_server_id)
  return intersection_server_id_;
}
inline void IntersectionRequest::set_intersection_server_id(::google::protobuf::uint32 value) {
  
  intersection_server_id_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionRequest.intersection_server_id)
}

// uint32 shard_size = 3;
inline void IntersectionRequest::clear_shard_size() {
  shard_size_ = 0u;
}
inline ::google::protobuf::uint32 IntersectionRequest::shard_size() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionRequest.shard_size)
  return shard_size_;
}
inline void IntersectionRequest::set_shard_size(::google::protobuf::uint32 value) {
  
  shard_size_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionRequest.shard_size)
}

// .intersection.UtilRequest util_request = 4;
inline bool IntersectionRequest::has_util_request() const {
  return this != internal_default_instance() && util_request_ != NULL;
}
inline void IntersectionRequest::clear_util_request() {
  if (GetArenaNoVirtual() == NULL && util_request_ != NULL) delete util_request_;
  util_request_ = NULL;
}
inline const ::intersection::UtilRequest& IntersectionRequest::util_request() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionRequest.util_request)
  return util_request_ != NULL ? *util_request_
                         : *::intersection::UtilRequest::internal_default_instance();
}
inline ::intersection::UtilRequest* IntersectionRequest::mutable_util_request() {
  
  if (util_request_ == NULL) {
    util_request_ = new ::intersection::UtilRequest;
  }
  // @@protoc_insertion_point(field_mutable:intersection.IntersectionRequest.util_request)
  return util_request_;
}
inline ::intersection::UtilRequest* IntersectionRequest::release_util_request() {
  // @@protoc_insertion_point(field_release:intersection.IntersectionRequest.util_request)
  
  ::intersection::UtilRequest* temp = util_request_;
  util_request_ = NULL;
  return temp;
}
inline void IntersectionRequest::set_allocated_util_request(::intersection::UtilRequest* util_request) {
  delete util_request_;
  util_request_ = util_request;
  if (util_request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:intersection.IntersectionRequest.util_request)
}

// uint64 request_id = 5;
inline void IntersectionRequest::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 IntersectionRequest::request_id() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionRequest.request_id)
  return request_id_;
}
inline void IntersectionRequest::set_request_id(::google::protobuf::uint64 value) {
  
  request_id_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionRequest.request_id)
}

// uint64 index_view = 6;
inline void IntersectionRequest::clear_index_view() {
  index_view_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 IntersectionRequest::index_view() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionRequest.index_view)
  return index_view_;
}
inline void IntersectionRequest::set_index_view(::google::protobuf::uint64 value) {
  
  index_view_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionRequest.index_view)
}

// -------------------------------------------------------------------

// TimingDataInMicro

// uint64 unpack_intersection_srv_req_time_in_micro = 1;
inline void TimingDataInMicro::clear_unpack_intersection_srv_req_time_in_micro() {
  unpack_intersection_srv_req_time_in_micro_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TimingDataInMicro::unpack_intersection_srv_req_time_in_micro() const {
  // @@protoc_insertion_point(field_get:intersection.TimingDataInMicro.unpack_intersection_srv_req_time_in_micro)
  return unpack_intersection_srv_req_time_in_micro_;
}
inline void TimingDataInMicro::set_unpack_intersection_srv_req_time_in_micro(::google::protobuf::uint64 value) {
  
  unpack_intersection_srv_req_time_in_micro_ = value;
  // @@protoc_insertion_point(field_set:intersection.TimingDataInMicro.unpack_intersection_srv_req_time_in_micro)
}

// uint64 calculate_intersection_time_in_micro = 2;
inline void TimingDataInMicro::clear_calculate_intersection_time_in_micro() {
  calculate_intersection_time_in_micro_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TimingDataInMicro::calculate_intersection_time_in_micro() const {
  // @@protoc_insertion_point(field_get:intersection.TimingDataInMicro.calculate_intersection_time_in_micro)
  return calculate_intersection_time_in_micro_;
}
inline void TimingDataInMicro::set_calculate_intersection_time_in_micro(::google::protobuf::uint64 value) {
  
  calculate_intersection_time_in_micro_ = value;
  // @@protoc_insertion_point(field_set:intersection.TimingDataInMicro.calculate_intersection_time_in_micro)
}

// uint64 pack_intersection_srv_resp_time_in_micro = 3;
inline void TimingDataInMicro::clear_pack_intersection_srv_resp_time_in_micro() {
  pack_intersection_srv_resp_time_in_micro_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TimingDataInMicro::pack_intersection_srv_resp_time_in_micro() const {
  // @@protoc_insertion_point(field_get:intersection.TimingDataInMicro.pack_intersection_srv_resp_time_in_micro)
  return pack_intersection_srv_resp_time_in_micro_;
}
inline void TimingDataInMicro::set_pack_intersection_srv_resp_time_in_micro(::google::protobuf::uint64 value) {
  
  pack_intersection_srv_resp_time_in_micro_ = value;
  // @@protoc_insertion_point(field_set:intersection.TimingDataInMicro.pack_intersection_srv_resp_time_in_micro)
}

// float cpu_util = 4;
inline void TimingDataInMicro::clear_cpu_util() {
  cpu_util_ = 0;
}
inline float TimingDataInMicro::cpu_util() const {
  // @@protoc_insertion_point(field_get:intersection.TimingDataInMicro.cpu_util)
  return cpu_util_;
}
inline void TimingDataInMicro::set_cpu_util(float value) {
  
  cpu_util_ = value;
  // @@protoc_insertion_point(field_set:intersection.TimingDataInMicro.cpu_util)
}

// -------------------------------------------------------------------

// UtilResponse

// bool util_present = 1;
inline void UtilResponse::clear_util_present() {
  util_present_ = false;
}
inline bool UtilResponse::util_present() const {
  // @@protoc_insertion_point(field_get:intersection.UtilResponse.util_present)
  return util_present_;
}
inline void UtilResponse::set_util_present(bool value) {
  
  util_present_ = value;
  // @@protoc_insertion_point(field_set:intersection.UtilResponse.util_present)
}

// uint64 user_time = 2;
inline void UtilResponse::clear_user_time() {
  user_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UtilResponse::user_time() const {
  // @@protoc_insertion_point(field_get:intersection.UtilResponse.user_time)
  return user_time_;
}
inline void UtilResponse::set_user_time(::google::protobuf::uint64 value) {
  
  user_time_ = value;
  // @@protoc_insertion_point(field_set:intersection.UtilResponse.user_time)
}

// uint64 system_time = 3;
inline void UtilResponse::clear_system_time() {
  system_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UtilResponse::system_time() const {
  // @@protoc_insertion_point(field_get:intersection.UtilResponse.system_time)
  return system_time_;
}
inline void UtilResponse::set_system_time(::google::protobuf::uint64 value) {
  
  system_time_ = value;
  // @@protoc_insertion_point(field_set:intersection.UtilResponse.system_time)
}

// uint64 io_time = 4;
inline void UtilResponse::clear_io_time() {
  io_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UtilResponse::io_time() const {
  // @@protoc_insertion_point(field_get:intersection.UtilResponse.io_time)
  return io_time_;
}
inline void UtilResponse::set_io_time(::google::protobuf::uint64 value) {
  
  io_time_ = value;
  // @@protoc_insertion_point(field_set:intersection.UtilResponse.io_time)
}

// uint64 idle_time = 5;
inline void UtilResponse::clear_idle_time() {
  idle_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UtilResponse::idle_time() const {
  // @@protoc_insertion_point(field_get:intersection.UtilResponse.idle_time)
  return idle_time_;
}
inline void UtilResponse::set_idle_time(::google::protobuf::uint64 value) {
  
  idle_time_ = value;
  // @@protoc_insertion_point(field_set:intersection.UtilResponse.idle_time)
}

// -------------------------------------------------------------------

// IntersectionResponse

// repeated uint64 doc_ids = 1;
inline int IntersectionResponse::doc_ids_size() const {
  return doc_ids_.size();
}
inline void IntersectionResponse::clear_doc_ids() {
  doc_ids_.Clear();
}
inline ::google::protobuf::uint64 IntersectionResponse::doc_ids(int index) const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionResponse.doc_ids)
  return doc_ids_.Get(index);
}
inline void IntersectionResponse::set_doc_ids(int index, ::google::protobuf::uint64 value) {
  doc_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:intersection.IntersectionResponse.doc_ids)
}
inline void IntersectionResponse::add_doc_ids(::google::protobuf::uint64 value) {
  doc_ids_.Add(value);
  // @@protoc_insertion_point(field_add:intersection.IntersectionResponse.doc_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
IntersectionResponse::doc_ids() const {
  // @@protoc_insertion_point(field_list:intersection.IntersectionResponse.doc_ids)
  return doc_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
IntersectionResponse::mutable_doc_ids() {
  // @@protoc_insertion_point(field_mutable_list:intersection.IntersectionResponse.doc_ids)
  return &doc_ids_;
}

// .intersection.TimingDataInMicro timing_data_in_micro = 2;
inline bool IntersectionResponse::has_timing_data_in_micro() const {
  return this != internal_default_instance() && timing_data_in_micro_ != NULL;
}
inline void IntersectionResponse::clear_timing_data_in_micro() {
  if (GetArenaNoVirtual() == NULL && timing_data_in_micro_ != NULL) delete timing_data_in_micro_;
  timing_data_in_micro_ = NULL;
}
inline const ::intersection::TimingDataInMicro& IntersectionResponse::timing_data_in_micro() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionResponse.timing_data_in_micro)
  return timing_data_in_micro_ != NULL ? *timing_data_in_micro_
                         : *::intersection::TimingDataInMicro::internal_default_instance();
}
inline ::intersection::TimingDataInMicro* IntersectionResponse::mutable_timing_data_in_micro() {
  
  if (timing_data_in_micro_ == NULL) {
    timing_data_in_micro_ = new ::intersection::TimingDataInMicro;
  }
  // @@protoc_insertion_point(field_mutable:intersection.IntersectionResponse.timing_data_in_micro)
  return timing_data_in_micro_;
}
inline ::intersection::TimingDataInMicro* IntersectionResponse::release_timing_data_in_micro() {
  // @@protoc_insertion_point(field_release:intersection.IntersectionResponse.timing_data_in_micro)
  
  ::intersection::TimingDataInMicro* temp = timing_data_in_micro_;
  timing_data_in_micro_ = NULL;
  return temp;
}
inline void IntersectionResponse::set_allocated_timing_data_in_micro(::intersection::TimingDataInMicro* timing_data_in_micro) {
  delete timing_data_in_micro_;
  timing_data_in_micro_ = timing_data_in_micro;
  if (timing_data_in_micro) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:intersection.IntersectionResponse.timing_data_in_micro)
}

// .intersection.UtilResponse util_response = 3;
inline bool IntersectionResponse::has_util_response() const {
  return this != internal_default_instance() && util_response_ != NULL;
}
inline void IntersectionResponse::clear_util_response() {
  if (GetArenaNoVirtual() == NULL && util_response_ != NULL) delete util_response_;
  util_response_ = NULL;
}
inline const ::intersection::UtilResponse& IntersectionResponse::util_response() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionResponse.util_response)
  return util_response_ != NULL ? *util_response_
                         : *::intersection::UtilResponse::internal_default_instance();
}
inline ::intersection::UtilResponse* IntersectionResponse::mutable_util_response() {
  
  if (util_response_ == NULL) {
    util_response_ = new ::intersection::UtilResponse;
  }
  // @@protoc_insertion_point(field_mutable:intersection.IntersectionResponse.util_response)
  return util_response_;
}
inline ::intersection::UtilResponse* IntersectionResponse::release_util_response() {
  // @@protoc_insertion_point(field_release:intersection.IntersectionResponse.util_response)
  
  ::intersection::UtilResponse* temp = util_response_;
  util_response_ = NULL;
  return temp;
}
inline void IntersectionResponse::set_allocated_util_response(::intersection::UtilResponse* util_response) {
  delete util_response_;
  util_response_ = util_response;
  if (util_response) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:intersection.IntersectionResponse.util_response)
}

// uint64 request_id = 4;
inline void IntersectionResponse::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 IntersectionResponse::request_id() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionResponse.request_id)
  return request_id_;
}
inline void IntersectionResponse::set_request_id(::google::protobuf::uint64 value) {
  
  request_id_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionResponse.request_id)
}

// uint64 recv_stamp = 5;
inline void IntersectionResponse::clear_recv_stamp() {
  recv_stamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 IntersectionResponse::recv_stamp() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionResponse.recv_stamp)
  return recv_stamp_;
}
inline void IntersectionResponse::set_recv_stamp(::google::protobuf::uint64 value) {
  
  recv_stamp_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionResponse.recv_stamp)
}

// uint64 send_stamp = 6;
inline void IntersectionResponse::clear_send_stamp() {
  send_stamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 IntersectionResponse::send_stamp() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionResponse.send_stamp)
  return send_stamp_;
}
inline void IntersectionResponse::set_send_stamp(::google::protobuf::uint64 value) {
  
  send_stamp_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionResponse.send_stamp)
}

// uint64 index_view = 7;
inline void IntersectionResponse::clear_index_view() {
  index_view_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 IntersectionResponse::index_view() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionResponse.index_view)
  return index_view_;
}
inline void IntersectionResponse::set_index_view(::google::protobuf::uint64 value) {
  
  index_view_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionResponse.index_view)
}

// uint32 request_server_id = 8;
inline void IntersectionResponse::clear_request_server_id() {
  request_server_id_ = 0u;
}
inline ::google::protobuf::uint32 IntersectionResponse::request_server_id() const {
  // @@protoc_insertion_point(field_get:intersection.IntersectionResponse.request_server_id)
  return request_server_id_;
}
inline void IntersectionResponse::set_request_server_id(::google::protobuf::uint32 value) {
  
  request_server_id_ = value;
  // @@protoc_insertion_point(field_set:intersection.IntersectionResponse.request_server_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace intersection

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_intersection_2eproto__INCLUDED
