// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: union.proto

#include "union.pb.h"
#include "union.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace union_service {

static const char* UnionService_method_names[] = {
  "/union_service.UnionService/Union",
};

std::unique_ptr< UnionService::Stub> UnionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< UnionService::Stub> stub(new UnionService::Stub(channel));
  return stub;
}

UnionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Union_(UnionService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UnionService::Stub::Union(::grpc::ClientContext* context, const ::union_service::UnionRequest& request, ::union_service::UnionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Union_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::union_service::UnionResponse>* UnionService::Stub::AsyncUnionRaw(::grpc::ClientContext* context, const ::union_service::UnionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::union_service::UnionResponse>::Create(channel_.get(), cq, rpcmethod_Union_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::union_service::UnionResponse>* UnionService::Stub::PrepareAsyncUnionRaw(::grpc::ClientContext* context, const ::union_service::UnionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::union_service::UnionResponse>::Create(channel_.get(), cq, rpcmethod_Union_, context, request, false);
}

UnionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UnionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UnionService::Service, ::union_service::UnionRequest, ::union_service::UnionResponse>(
          std::mem_fn(&UnionService::Service::Union), this)));
}

UnionService::Service::~Service() {
}

::grpc::Status UnionService::Service::Union(::grpc::ServerContext* context, const ::union_service::UnionRequest* request, ::union_service::UnionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace union_service

