// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: union.proto

#ifndef PROTOBUF_union_2eproto__INCLUDED
#define PROTOBUF_union_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
namespace google {
namespace protobuf {
class DescriptorProto;
class DescriptorProtoDefaultTypeInternal;
extern DescriptorProtoDefaultTypeInternal _DescriptorProto_default_instance_;
class DescriptorProto_ExtensionRange;
class DescriptorProto_ExtensionRangeDefaultTypeInternal;
extern DescriptorProto_ExtensionRangeDefaultTypeInternal _DescriptorProto_ExtensionRange_default_instance_;
class DescriptorProto_ReservedRange;
class DescriptorProto_ReservedRangeDefaultTypeInternal;
extern DescriptorProto_ReservedRangeDefaultTypeInternal _DescriptorProto_ReservedRange_default_instance_;
class EnumDescriptorProto;
class EnumDescriptorProtoDefaultTypeInternal;
extern EnumDescriptorProtoDefaultTypeInternal _EnumDescriptorProto_default_instance_;
class EnumOptions;
class EnumOptionsDefaultTypeInternal;
extern EnumOptionsDefaultTypeInternal _EnumOptions_default_instance_;
class EnumValueDescriptorProto;
class EnumValueDescriptorProtoDefaultTypeInternal;
extern EnumValueDescriptorProtoDefaultTypeInternal _EnumValueDescriptorProto_default_instance_;
class EnumValueOptions;
class EnumValueOptionsDefaultTypeInternal;
extern EnumValueOptionsDefaultTypeInternal _EnumValueOptions_default_instance_;
class FieldDescriptorProto;
class FieldDescriptorProtoDefaultTypeInternal;
extern FieldDescriptorProtoDefaultTypeInternal _FieldDescriptorProto_default_instance_;
class FieldOptions;
class FieldOptionsDefaultTypeInternal;
extern FieldOptionsDefaultTypeInternal _FieldOptions_default_instance_;
class FileDescriptorProto;
class FileDescriptorProtoDefaultTypeInternal;
extern FileDescriptorProtoDefaultTypeInternal _FileDescriptorProto_default_instance_;
class FileDescriptorSet;
class FileDescriptorSetDefaultTypeInternal;
extern FileDescriptorSetDefaultTypeInternal _FileDescriptorSet_default_instance_;
class FileOptions;
class FileOptionsDefaultTypeInternal;
extern FileOptionsDefaultTypeInternal _FileOptions_default_instance_;
class GeneratedCodeInfo;
class GeneratedCodeInfoDefaultTypeInternal;
extern GeneratedCodeInfoDefaultTypeInternal _GeneratedCodeInfo_default_instance_;
class GeneratedCodeInfo_Annotation;
class GeneratedCodeInfo_AnnotationDefaultTypeInternal;
extern GeneratedCodeInfo_AnnotationDefaultTypeInternal _GeneratedCodeInfo_Annotation_default_instance_;
class MessageOptions;
class MessageOptionsDefaultTypeInternal;
extern MessageOptionsDefaultTypeInternal _MessageOptions_default_instance_;
class MethodDescriptorProto;
class MethodDescriptorProtoDefaultTypeInternal;
extern MethodDescriptorProtoDefaultTypeInternal _MethodDescriptorProto_default_instance_;
class MethodOptions;
class MethodOptionsDefaultTypeInternal;
extern MethodOptionsDefaultTypeInternal _MethodOptions_default_instance_;
class OneofDescriptorProto;
class OneofDescriptorProtoDefaultTypeInternal;
extern OneofDescriptorProtoDefaultTypeInternal _OneofDescriptorProto_default_instance_;
class OneofOptions;
class OneofOptionsDefaultTypeInternal;
extern OneofOptionsDefaultTypeInternal _OneofOptions_default_instance_;
class ServiceDescriptorProto;
class ServiceDescriptorProtoDefaultTypeInternal;
extern ServiceDescriptorProtoDefaultTypeInternal _ServiceDescriptorProto_default_instance_;
class ServiceOptions;
class ServiceOptionsDefaultTypeInternal;
extern ServiceOptionsDefaultTypeInternal _ServiceOptions_default_instance_;
class SourceCodeInfo;
class SourceCodeInfoDefaultTypeInternal;
extern SourceCodeInfoDefaultTypeInternal _SourceCodeInfo_default_instance_;
class SourceCodeInfo_Location;
class SourceCodeInfo_LocationDefaultTypeInternal;
extern SourceCodeInfo_LocationDefaultTypeInternal _SourceCodeInfo_Location_default_instance_;
class UninterpretedOption;
class UninterpretedOptionDefaultTypeInternal;
extern UninterpretedOptionDefaultTypeInternal _UninterpretedOption_default_instance_;
class UninterpretedOption_NamePart;
class UninterpretedOption_NamePartDefaultTypeInternal;
extern UninterpretedOption_NamePartDefaultTypeInternal _UninterpretedOption_NamePart_default_instance_;
}  // namespace protobuf
}  // namespace google
namespace union_service {
class UnionRequest;
class UnionRequestDefaultTypeInternal;
extern UnionRequestDefaultTypeInternal _UnionRequest_default_instance_;
class UnionResponse;
class UnionResponseDefaultTypeInternal;
extern UnionResponseDefaultTypeInternal _UnionResponse_default_instance_;
class Util;
class UtilDefaultTypeInternal;
extern UtilDefaultTypeInternal _Util_default_instance_;
class UtilRequest;
class UtilRequestDefaultTypeInternal;
extern UtilRequestDefaultTypeInternal _UtilRequest_default_instance_;
class UtilResponse;
class UtilResponseDefaultTypeInternal;
extern UtilResponseDefaultTypeInternal _UtilResponse_default_instance_;
}  // namespace union_service

namespace union_service {

namespace protobuf_union_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_union_2eproto

// ===================================================================

class UtilRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:union_service.UtilRequest) */ {
 public:
  UtilRequest();
  virtual ~UtilRequest();

  UtilRequest(const UtilRequest& from);

  inline UtilRequest& operator=(const UtilRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UtilRequest& default_instance();

  static inline const UtilRequest* internal_default_instance() {
    return reinterpret_cast<const UtilRequest*>(
               &_UtilRequest_default_instance_);
  }

  void Swap(UtilRequest* other);

  // implements Message ----------------------------------------------

  inline UtilRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UtilRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UtilRequest& from);
  void MergeFrom(const UtilRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UtilRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool util_request = 1;
  void clear_util_request();
  static const int kUtilRequestFieldNumber = 1;
  bool util_request() const;
  void set_util_request(bool value);

  // @@protoc_insertion_point(class_scope:union_service.UtilRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool util_request_;
  mutable int _cached_size_;
  friend struct  protobuf_union_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UnionRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:union_service.UnionRequest) */ {
 public:
  UnionRequest();
  virtual ~UnionRequest();

  UnionRequest(const UnionRequest& from);

  inline UnionRequest& operator=(const UnionRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UnionRequest& default_instance();

  static inline const UnionRequest* internal_default_instance() {
    return reinterpret_cast<const UnionRequest*>(
               &_UnionRequest_default_instance_);
  }

  void Swap(UnionRequest* other);

  // implements Message ----------------------------------------------

  inline UnionRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UnionRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UnionRequest& from);
  void MergeFrom(const UnionRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UnionRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 word_ids = 1;
  int word_ids_size() const;
  void clear_word_ids();
  static const int kWordIdsFieldNumber = 1;
  ::google::protobuf::uint64 word_ids(int index) const;
  void set_word_ids(int index, ::google::protobuf::uint64 value);
  void add_word_ids(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      word_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_word_ids();

  // .union_service.UtilRequest util_request = 2;
  bool has_util_request() const;
  void clear_util_request();
  static const int kUtilRequestFieldNumber = 2;
  const ::union_service::UtilRequest& util_request() const;
  ::union_service::UtilRequest* mutable_util_request();
  ::union_service::UtilRequest* release_util_request();
  void set_allocated_util_request(::union_service::UtilRequest* util_request);

  // uint64 resp_time = 4;
  void clear_resp_time();
  static const int kRespTimeFieldNumber = 4;
  ::google::protobuf::uint64 resp_time() const;
  void set_resp_time(::google::protobuf::uint64 value);

  // bool last_request = 3;
  void clear_last_request();
  static const int kLastRequestFieldNumber = 3;
  bool last_request() const;
  void set_last_request(bool value);

  // bool kill = 5;
  void clear_kill();
  static const int kKillFieldNumber = 5;
  bool kill() const;
  void set_kill(bool value);

  // uint32 load = 7;
  void clear_load();
  static const int kLoadFieldNumber = 7;
  ::google::protobuf::uint32 load() const;
  void set_load(::google::protobuf::uint32 value);

  // uint64 request_id = 6;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 6;
  ::google::protobuf::uint64 request_id() const;
  void set_request_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:union_service.UnionRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > word_ids_;
  mutable int _word_ids_cached_byte_size_;
  ::union_service::UtilRequest* util_request_;
  ::google::protobuf::uint64 resp_time_;
  bool last_request_;
  bool kill_;
  ::google::protobuf::uint32 load_;
  ::google::protobuf::uint64 request_id_;
  mutable int _cached_size_;
  friend struct  protobuf_union_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Util : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:union_service.Util) */ {
 public:
  Util();
  virtual ~Util();

  Util(const Util& from);

  inline Util& operator=(const Util& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Util& default_instance();

  static inline const Util* internal_default_instance() {
    return reinterpret_cast<const Util*>(
               &_Util_default_instance_);
  }

  void Swap(Util* other);

  // implements Message ----------------------------------------------

  inline Util* New() const PROTOBUF_FINAL { return New(NULL); }

  Util* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Util& from);
  void MergeFrom(const Util& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Util* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 user_time = 1;
  void clear_user_time();
  static const int kUserTimeFieldNumber = 1;
  ::google::protobuf::uint64 user_time() const;
  void set_user_time(::google::protobuf::uint64 value);

  // uint64 system_time = 2;
  void clear_system_time();
  static const int kSystemTimeFieldNumber = 2;
  ::google::protobuf::uint64 system_time() const;
  void set_system_time(::google::protobuf::uint64 value);

  // uint64 io_time = 3;
  void clear_io_time();
  static const int kIoTimeFieldNumber = 3;
  ::google::protobuf::uint64 io_time() const;
  void set_io_time(::google::protobuf::uint64 value);

  // uint64 idle_time = 4;
  void clear_idle_time();
  static const int kIdleTimeFieldNumber = 4;
  ::google::protobuf::uint64 idle_time() const;
  void set_idle_time(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:union_service.Util)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 user_time_;
  ::google::protobuf::uint64 system_time_;
  ::google::protobuf::uint64 io_time_;
  ::google::protobuf::uint64 idle_time_;
  mutable int _cached_size_;
  friend struct  protobuf_union_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UtilResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:union_service.UtilResponse) */ {
 public:
  UtilResponse();
  virtual ~UtilResponse();

  UtilResponse(const UtilResponse& from);

  inline UtilResponse& operator=(const UtilResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UtilResponse& default_instance();

  static inline const UtilResponse* internal_default_instance() {
    return reinterpret_cast<const UtilResponse*>(
               &_UtilResponse_default_instance_);
  }

  void Swap(UtilResponse* other);

  // implements Message ----------------------------------------------

  inline UtilResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  UtilResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UtilResponse& from);
  void MergeFrom(const UtilResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UtilResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .union_service.Util intersection_srv_util = 2;
  int intersection_srv_util_size() const;
  void clear_intersection_srv_util();
  static const int kIntersectionSrvUtilFieldNumber = 2;
  const ::union_service::Util& intersection_srv_util(int index) const;
  ::union_service::Util* mutable_intersection_srv_util(int index);
  ::union_service::Util* add_intersection_srv_util();
  ::google::protobuf::RepeatedPtrField< ::union_service::Util >*
      mutable_intersection_srv_util();
  const ::google::protobuf::RepeatedPtrField< ::union_service::Util >&
      intersection_srv_util() const;

  // .union_service.Util union_util = 3;
  bool has_union_util() const;
  void clear_union_util();
  static const int kUnionUtilFieldNumber = 3;
  const ::union_service::Util& union_util() const;
  ::union_service::Util* mutable_union_util();
  ::union_service::Util* release_union_util();
  void set_allocated_union_util(::union_service::Util* union_util);

  // bool util_present = 1;
  void clear_util_present();
  static const int kUtilPresentFieldNumber = 1;
  bool util_present() const;
  void set_util_present(bool value);

  // @@protoc_insertion_point(class_scope:union_service.UtilResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::union_service::Util > intersection_srv_util_;
  ::union_service::Util* union_util_;
  bool util_present_;
  mutable int _cached_size_;
  friend struct  protobuf_union_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UnionResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:union_service.UnionResponse) */ {
 public:
  UnionResponse();
  virtual ~UnionResponse();

  UnionResponse(const UnionResponse& from);

  inline UnionResponse& operator=(const UnionResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UnionResponse& default_instance();

  static inline const UnionResponse* internal_default_instance() {
    return reinterpret_cast<const UnionResponse*>(
               &_UnionResponse_default_instance_);
  }

  void Swap(UnionResponse* other);

  // implements Message ----------------------------------------------

  inline UnionResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  UnionResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UnionResponse& from);
  void MergeFrom(const UnionResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UnionResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 doc_ids = 1;
  int doc_ids_size() const;
  void clear_doc_ids();
  static const int kDocIdsFieldNumber = 1;
  ::google::protobuf::uint64 doc_ids(int index) const;
  void set_doc_ids(int index, ::google::protobuf::uint64 value);
  void add_doc_ids(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      doc_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_doc_ids();

  // .union_service.UtilResponse util_response = 14;
  bool has_util_response() const;
  void clear_util_response();
  static const int kUtilResponseFieldNumber = 14;
  const ::union_service::UtilResponse& util_response() const;
  ::union_service::UtilResponse* mutable_util_response();
  ::union_service::UtilResponse* release_util_response();
  void set_allocated_util_response(::union_service::UtilResponse* util_response);

  // uint64 create_union_req_time = 2;
  void clear_create_union_req_time();
  static const int kCreateUnionReqTimeFieldNumber = 2;
  ::google::protobuf::uint64 create_union_req_time() const;
  void set_create_union_req_time(::google::protobuf::uint64 value);

  // uint64 unpack_union_req_time = 3;
  void clear_unpack_union_req_time();
  static const int kUnpackUnionReqTimeFieldNumber = 3;
  ::google::protobuf::uint64 unpack_union_req_time() const;
  void set_unpack_union_req_time(::google::protobuf::uint64 value);

  // uint64 update_union_util_time = 4;
  void clear_update_union_util_time();
  static const int kUpdateUnionUtilTimeFieldNumber = 4;
  ::google::protobuf::uint64 update_union_util_time() const;
  void set_update_union_util_time(::google::protobuf::uint64 value);

  // uint64 get_intersection_srv_responses_time = 5;
  void clear_get_intersection_srv_responses_time();
  static const int kGetIntersectionSrvResponsesTimeFieldNumber = 5;
  ::google::protobuf::uint64 get_intersection_srv_responses_time() const;
  void set_get_intersection_srv_responses_time(::google::protobuf::uint64 value);

  // uint64 create_intersection_srv_req_time = 6;
  void clear_create_intersection_srv_req_time();
  static const int kCreateIntersectionSrvReqTimeFieldNumber = 6;
  ::google::protobuf::uint64 create_intersection_srv_req_time() const;
  void set_create_intersection_srv_req_time(::google::protobuf::uint64 value);

  // uint64 unpack_intersection_srv_resp_time = 7;
  void clear_unpack_intersection_srv_resp_time();
  static const int kUnpackIntersectionSrvRespTimeFieldNumber = 7;
  ::google::protobuf::uint64 unpack_intersection_srv_resp_time() const;
  void set_unpack_intersection_srv_resp_time(::google::protobuf::uint64 value);

  // uint64 unpack_intersection_srv_req_time = 8;
  void clear_unpack_intersection_srv_req_time();
  static const int kUnpackIntersectionSrvReqTimeFieldNumber = 8;
  ::google::protobuf::uint64 unpack_intersection_srv_req_time() const;
  void set_unpack_intersection_srv_req_time(::google::protobuf::uint64 value);

  // uint64 calculate_intersection_time = 9;
  void clear_calculate_intersection_time();
  static const int kCalculateIntersectionTimeFieldNumber = 9;
  ::google::protobuf::uint64 calculate_intersection_time() const;
  void set_calculate_intersection_time(::google::protobuf::uint64 value);

  // uint64 pack_intersection_srv_resp_time = 10;
  void clear_pack_intersection_srv_resp_time();
  static const int kPackIntersectionSrvRespTimeFieldNumber = 10;
  ::google::protobuf::uint64 pack_intersection_srv_resp_time() const;
  void set_pack_intersection_srv_resp_time(::google::protobuf::uint64 value);

  // uint64 calculate_union_time = 11;
  void clear_calculate_union_time();
  static const int kCalculateUnionTimeFieldNumber = 11;
  ::google::protobuf::uint64 calculate_union_time() const;
  void set_calculate_union_time(::google::protobuf::uint64 value);

  // uint64 pack_union_resp_time = 12;
  void clear_pack_union_resp_time();
  static const int kPackUnionRespTimeFieldNumber = 12;
  ::google::protobuf::uint64 pack_union_resp_time() const;
  void set_pack_union_resp_time(::google::protobuf::uint64 value);

  // uint64 resp_time = 15;
  void clear_resp_time();
  static const int kRespTimeFieldNumber = 15;
  ::google::protobuf::uint64 resp_time() const;
  void set_resp_time(::google::protobuf::uint64 value);

  // uint64 union_time = 16;
  void clear_union_time();
  static const int kUnionTimeFieldNumber = 16;
  ::google::protobuf::uint64 union_time() const;
  void set_union_time(::google::protobuf::uint64 value);

  // uint64 start_stamp = 17;
  void clear_start_stamp();
  static const int kStartStampFieldNumber = 17;
  ::google::protobuf::uint64 start_stamp() const;
  void set_start_stamp(::google::protobuf::uint64 value);

  // uint64 end_stamp = 18;
  void clear_end_stamp();
  static const int kEndStampFieldNumber = 18;
  ::google::protobuf::uint64 end_stamp() const;
  void set_end_stamp(::google::protobuf::uint64 value);

  // uint32 number_of_intersection_servers = 13;
  void clear_number_of_intersection_servers();
  static const int kNumberOfIntersectionServersFieldNumber = 13;
  ::google::protobuf::uint32 number_of_intersection_servers() const;
  void set_number_of_intersection_servers(::google::protobuf::uint32 value);

  // bool kill_ack = 23;
  void clear_kill_ack();
  static const int kKillAckFieldNumber = 23;
  bool kill_ack() const;
  void set_kill_ack(bool value);

  // uint64 request_id = 19;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 19;
  ::google::protobuf::uint64 request_id() const;
  void set_request_id(::google::protobuf::uint64 value);

  // uint64 num_inline = 20;
  void clear_num_inline();
  static const int kNumInlineFieldNumber = 20;
  ::google::protobuf::uint64 num_inline() const;
  void set_num_inline(::google::protobuf::uint64 value);

  // uint64 num_workers = 21;
  void clear_num_workers();
  static const int kNumWorkersFieldNumber = 21;
  ::google::protobuf::uint64 num_workers() const;
  void set_num_workers(::google::protobuf::uint64 value);

  // uint64 num_resp = 22;
  void clear_num_resp();
  static const int kNumRespFieldNumber = 22;
  ::google::protobuf::uint64 num_resp() const;
  void set_num_resp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:union_service.UnionResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > doc_ids_;
  mutable int _doc_ids_cached_byte_size_;
  ::union_service::UtilResponse* util_response_;
  ::google::protobuf::uint64 create_union_req_time_;
  ::google::protobuf::uint64 unpack_union_req_time_;
  ::google::protobuf::uint64 update_union_util_time_;
  ::google::protobuf::uint64 get_intersection_srv_responses_time_;
  ::google::protobuf::uint64 create_intersection_srv_req_time_;
  ::google::protobuf::uint64 unpack_intersection_srv_resp_time_;
  ::google::protobuf::uint64 unpack_intersection_srv_req_time_;
  ::google::protobuf::uint64 calculate_intersection_time_;
  ::google::protobuf::uint64 pack_intersection_srv_resp_time_;
  ::google::protobuf::uint64 calculate_union_time_;
  ::google::protobuf::uint64 pack_union_resp_time_;
  ::google::protobuf::uint64 resp_time_;
  ::google::protobuf::uint64 union_time_;
  ::google::protobuf::uint64 start_stamp_;
  ::google::protobuf::uint64 end_stamp_;
  ::google::protobuf::uint32 number_of_intersection_servers_;
  bool kill_ack_;
  ::google::protobuf::uint64 request_id_;
  ::google::protobuf::uint64 num_inline_;
  ::google::protobuf::uint64 num_workers_;
  ::google::protobuf::uint64 num_resp_;
  mutable int _cached_size_;
  friend struct  protobuf_union_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UtilRequest

// bool util_request = 1;
inline void UtilRequest::clear_util_request() {
  util_request_ = false;
}
inline bool UtilRequest::util_request() const {
  // @@protoc_insertion_point(field_get:union_service.UtilRequest.util_request)
  return util_request_;
}
inline void UtilRequest::set_util_request(bool value) {
  
  util_request_ = value;
  // @@protoc_insertion_point(field_set:union_service.UtilRequest.util_request)
}

// -------------------------------------------------------------------

// UnionRequest

// repeated uint64 word_ids = 1;
inline int UnionRequest::word_ids_size() const {
  return word_ids_.size();
}
inline void UnionRequest::clear_word_ids() {
  word_ids_.Clear();
}
inline ::google::protobuf::uint64 UnionRequest::word_ids(int index) const {
  // @@protoc_insertion_point(field_get:union_service.UnionRequest.word_ids)
  return word_ids_.Get(index);
}
inline void UnionRequest::set_word_ids(int index, ::google::protobuf::uint64 value) {
  word_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:union_service.UnionRequest.word_ids)
}
inline void UnionRequest::add_word_ids(::google::protobuf::uint64 value) {
  word_ids_.Add(value);
  // @@protoc_insertion_point(field_add:union_service.UnionRequest.word_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
UnionRequest::word_ids() const {
  // @@protoc_insertion_point(field_list:union_service.UnionRequest.word_ids)
  return word_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
UnionRequest::mutable_word_ids() {
  // @@protoc_insertion_point(field_mutable_list:union_service.UnionRequest.word_ids)
  return &word_ids_;
}

// .union_service.UtilRequest util_request = 2;
inline bool UnionRequest::has_util_request() const {
  return this != internal_default_instance() && util_request_ != NULL;
}
inline void UnionRequest::clear_util_request() {
  if (GetArenaNoVirtual() == NULL && util_request_ != NULL) delete util_request_;
  util_request_ = NULL;
}
inline const ::union_service::UtilRequest& UnionRequest::util_request() const {
  // @@protoc_insertion_point(field_get:union_service.UnionRequest.util_request)
  return util_request_ != NULL ? *util_request_
                         : *::union_service::UtilRequest::internal_default_instance();
}
inline ::union_service::UtilRequest* UnionRequest::mutable_util_request() {
  
  if (util_request_ == NULL) {
    util_request_ = new ::union_service::UtilRequest;
  }
  // @@protoc_insertion_point(field_mutable:union_service.UnionRequest.util_request)
  return util_request_;
}
inline ::union_service::UtilRequest* UnionRequest::release_util_request() {
  // @@protoc_insertion_point(field_release:union_service.UnionRequest.util_request)
  
  ::union_service::UtilRequest* temp = util_request_;
  util_request_ = NULL;
  return temp;
}
inline void UnionRequest::set_allocated_util_request(::union_service::UtilRequest* util_request) {
  delete util_request_;
  util_request_ = util_request;
  if (util_request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:union_service.UnionRequest.util_request)
}

// bool last_request = 3;
inline void UnionRequest::clear_last_request() {
  last_request_ = false;
}
inline bool UnionRequest::last_request() const {
  // @@protoc_insertion_point(field_get:union_service.UnionRequest.last_request)
  return last_request_;
}
inline void UnionRequest::set_last_request(bool value) {
  
  last_request_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionRequest.last_request)
}

// uint64 resp_time = 4;
inline void UnionRequest::clear_resp_time() {
  resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionRequest::resp_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionRequest.resp_time)
  return resp_time_;
}
inline void UnionRequest::set_resp_time(::google::protobuf::uint64 value) {
  
  resp_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionRequest.resp_time)
}

// bool kill = 5;
inline void UnionRequest::clear_kill() {
  kill_ = false;
}
inline bool UnionRequest::kill() const {
  // @@protoc_insertion_point(field_get:union_service.UnionRequest.kill)
  return kill_;
}
inline void UnionRequest::set_kill(bool value) {
  
  kill_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionRequest.kill)
}

// uint64 request_id = 6;
inline void UnionRequest::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionRequest::request_id() const {
  // @@protoc_insertion_point(field_get:union_service.UnionRequest.request_id)
  return request_id_;
}
inline void UnionRequest::set_request_id(::google::protobuf::uint64 value) {
  
  request_id_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionRequest.request_id)
}

// uint32 load = 7;
inline void UnionRequest::clear_load() {
  load_ = 0u;
}
inline ::google::protobuf::uint32 UnionRequest::load() const {
  // @@protoc_insertion_point(field_get:union_service.UnionRequest.load)
  return load_;
}
inline void UnionRequest::set_load(::google::protobuf::uint32 value) {
  
  load_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionRequest.load)
}

// -------------------------------------------------------------------

// Util

// uint64 user_time = 1;
inline void Util::clear_user_time() {
  user_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Util::user_time() const {
  // @@protoc_insertion_point(field_get:union_service.Util.user_time)
  return user_time_;
}
inline void Util::set_user_time(::google::protobuf::uint64 value) {
  
  user_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.Util.user_time)
}

// uint64 system_time = 2;
inline void Util::clear_system_time() {
  system_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Util::system_time() const {
  // @@protoc_insertion_point(field_get:union_service.Util.system_time)
  return system_time_;
}
inline void Util::set_system_time(::google::protobuf::uint64 value) {
  
  system_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.Util.system_time)
}

// uint64 io_time = 3;
inline void Util::clear_io_time() {
  io_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Util::io_time() const {
  // @@protoc_insertion_point(field_get:union_service.Util.io_time)
  return io_time_;
}
inline void Util::set_io_time(::google::protobuf::uint64 value) {
  
  io_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.Util.io_time)
}

// uint64 idle_time = 4;
inline void Util::clear_idle_time() {
  idle_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Util::idle_time() const {
  // @@protoc_insertion_point(field_get:union_service.Util.idle_time)
  return idle_time_;
}
inline void Util::set_idle_time(::google::protobuf::uint64 value) {
  
  idle_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.Util.idle_time)
}

// -------------------------------------------------------------------

// UtilResponse

// bool util_present = 1;
inline void UtilResponse::clear_util_present() {
  util_present_ = false;
}
inline bool UtilResponse::util_present() const {
  // @@protoc_insertion_point(field_get:union_service.UtilResponse.util_present)
  return util_present_;
}
inline void UtilResponse::set_util_present(bool value) {
  
  util_present_ = value;
  // @@protoc_insertion_point(field_set:union_service.UtilResponse.util_present)
}

// repeated .union_service.Util intersection_srv_util = 2;
inline int UtilResponse::intersection_srv_util_size() const {
  return intersection_srv_util_.size();
}
inline void UtilResponse::clear_intersection_srv_util() {
  intersection_srv_util_.Clear();
}
inline const ::union_service::Util& UtilResponse::intersection_srv_util(int index) const {
  // @@protoc_insertion_point(field_get:union_service.UtilResponse.intersection_srv_util)
  return intersection_srv_util_.Get(index);
}
inline ::union_service::Util* UtilResponse::mutable_intersection_srv_util(int index) {
  // @@protoc_insertion_point(field_mutable:union_service.UtilResponse.intersection_srv_util)
  return intersection_srv_util_.Mutable(index);
}
inline ::union_service::Util* UtilResponse::add_intersection_srv_util() {
  // @@protoc_insertion_point(field_add:union_service.UtilResponse.intersection_srv_util)
  return intersection_srv_util_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::union_service::Util >*
UtilResponse::mutable_intersection_srv_util() {
  // @@protoc_insertion_point(field_mutable_list:union_service.UtilResponse.intersection_srv_util)
  return &intersection_srv_util_;
}
inline const ::google::protobuf::RepeatedPtrField< ::union_service::Util >&
UtilResponse::intersection_srv_util() const {
  // @@protoc_insertion_point(field_list:union_service.UtilResponse.intersection_srv_util)
  return intersection_srv_util_;
}

// .union_service.Util union_util = 3;
inline bool UtilResponse::has_union_util() const {
  return this != internal_default_instance() && union_util_ != NULL;
}
inline void UtilResponse::clear_union_util() {
  if (GetArenaNoVirtual() == NULL && union_util_ != NULL) delete union_util_;
  union_util_ = NULL;
}
inline const ::union_service::Util& UtilResponse::union_util() const {
  // @@protoc_insertion_point(field_get:union_service.UtilResponse.union_util)
  return union_util_ != NULL ? *union_util_
                         : *::union_service::Util::internal_default_instance();
}
inline ::union_service::Util* UtilResponse::mutable_union_util() {
  
  if (union_util_ == NULL) {
    union_util_ = new ::union_service::Util;
  }
  // @@protoc_insertion_point(field_mutable:union_service.UtilResponse.union_util)
  return union_util_;
}
inline ::union_service::Util* UtilResponse::release_union_util() {
  // @@protoc_insertion_point(field_release:union_service.UtilResponse.union_util)
  
  ::union_service::Util* temp = union_util_;
  union_util_ = NULL;
  return temp;
}
inline void UtilResponse::set_allocated_union_util(::union_service::Util* union_util) {
  delete union_util_;
  union_util_ = union_util;
  if (union_util) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:union_service.UtilResponse.union_util)
}

// -------------------------------------------------------------------

// UnionResponse

// repeated uint64 doc_ids = 1;
inline int UnionResponse::doc_ids_size() const {
  return doc_ids_.size();
}
inline void UnionResponse::clear_doc_ids() {
  doc_ids_.Clear();
}
inline ::google::protobuf::uint64 UnionResponse::doc_ids(int index) const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.doc_ids)
  return doc_ids_.Get(index);
}
inline void UnionResponse::set_doc_ids(int index, ::google::protobuf::uint64 value) {
  doc_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.doc_ids)
}
inline void UnionResponse::add_doc_ids(::google::protobuf::uint64 value) {
  doc_ids_.Add(value);
  // @@protoc_insertion_point(field_add:union_service.UnionResponse.doc_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
UnionResponse::doc_ids() const {
  // @@protoc_insertion_point(field_list:union_service.UnionResponse.doc_ids)
  return doc_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
UnionResponse::mutable_doc_ids() {
  // @@protoc_insertion_point(field_mutable_list:union_service.UnionResponse.doc_ids)
  return &doc_ids_;
}

// uint64 create_union_req_time = 2;
inline void UnionResponse::clear_create_union_req_time() {
  create_union_req_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::create_union_req_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.create_union_req_time)
  return create_union_req_time_;
}
inline void UnionResponse::set_create_union_req_time(::google::protobuf::uint64 value) {
  
  create_union_req_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.create_union_req_time)
}

// uint64 unpack_union_req_time = 3;
inline void UnionResponse::clear_unpack_union_req_time() {
  unpack_union_req_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::unpack_union_req_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.unpack_union_req_time)
  return unpack_union_req_time_;
}
inline void UnionResponse::set_unpack_union_req_time(::google::protobuf::uint64 value) {
  
  unpack_union_req_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.unpack_union_req_time)
}

// uint64 update_union_util_time = 4;
inline void UnionResponse::clear_update_union_util_time() {
  update_union_util_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::update_union_util_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.update_union_util_time)
  return update_union_util_time_;
}
inline void UnionResponse::set_update_union_util_time(::google::protobuf::uint64 value) {
  
  update_union_util_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.update_union_util_time)
}

// uint64 get_intersection_srv_responses_time = 5;
inline void UnionResponse::clear_get_intersection_srv_responses_time() {
  get_intersection_srv_responses_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::get_intersection_srv_responses_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.get_intersection_srv_responses_time)
  return get_intersection_srv_responses_time_;
}
inline void UnionResponse::set_get_intersection_srv_responses_time(::google::protobuf::uint64 value) {
  
  get_intersection_srv_responses_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.get_intersection_srv_responses_time)
}

// uint64 create_intersection_srv_req_time = 6;
inline void UnionResponse::clear_create_intersection_srv_req_time() {
  create_intersection_srv_req_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::create_intersection_srv_req_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.create_intersection_srv_req_time)
  return create_intersection_srv_req_time_;
}
inline void UnionResponse::set_create_intersection_srv_req_time(::google::protobuf::uint64 value) {
  
  create_intersection_srv_req_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.create_intersection_srv_req_time)
}

// uint64 unpack_intersection_srv_resp_time = 7;
inline void UnionResponse::clear_unpack_intersection_srv_resp_time() {
  unpack_intersection_srv_resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::unpack_intersection_srv_resp_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.unpack_intersection_srv_resp_time)
  return unpack_intersection_srv_resp_time_;
}
inline void UnionResponse::set_unpack_intersection_srv_resp_time(::google::protobuf::uint64 value) {
  
  unpack_intersection_srv_resp_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.unpack_intersection_srv_resp_time)
}

// uint64 unpack_intersection_srv_req_time = 8;
inline void UnionResponse::clear_unpack_intersection_srv_req_time() {
  unpack_intersection_srv_req_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::unpack_intersection_srv_req_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.unpack_intersection_srv_req_time)
  return unpack_intersection_srv_req_time_;
}
inline void UnionResponse::set_unpack_intersection_srv_req_time(::google::protobuf::uint64 value) {
  
  unpack_intersection_srv_req_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.unpack_intersection_srv_req_time)
}

// uint64 calculate_intersection_time = 9;
inline void UnionResponse::clear_calculate_intersection_time() {
  calculate_intersection_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::calculate_intersection_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.calculate_intersection_time)
  return calculate_intersection_time_;
}
inline void UnionResponse::set_calculate_intersection_time(::google::protobuf::uint64 value) {
  
  calculate_intersection_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.calculate_intersection_time)
}

// uint64 pack_intersection_srv_resp_time = 10;
inline void UnionResponse::clear_pack_intersection_srv_resp_time() {
  pack_intersection_srv_resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::pack_intersection_srv_resp_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.pack_intersection_srv_resp_time)
  return pack_intersection_srv_resp_time_;
}
inline void UnionResponse::set_pack_intersection_srv_resp_time(::google::protobuf::uint64 value) {
  
  pack_intersection_srv_resp_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.pack_intersection_srv_resp_time)
}

// uint64 calculate_union_time = 11;
inline void UnionResponse::clear_calculate_union_time() {
  calculate_union_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::calculate_union_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.calculate_union_time)
  return calculate_union_time_;
}
inline void UnionResponse::set_calculate_union_time(::google::protobuf::uint64 value) {
  
  calculate_union_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.calculate_union_time)
}

// uint64 pack_union_resp_time = 12;
inline void UnionResponse::clear_pack_union_resp_time() {
  pack_union_resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::pack_union_resp_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.pack_union_resp_time)
  return pack_union_resp_time_;
}
inline void UnionResponse::set_pack_union_resp_time(::google::protobuf::uint64 value) {
  
  pack_union_resp_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.pack_union_resp_time)
}

// uint32 number_of_intersection_servers = 13;
inline void UnionResponse::clear_number_of_intersection_servers() {
  number_of_intersection_servers_ = 0u;
}
inline ::google::protobuf::uint32 UnionResponse::number_of_intersection_servers() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.number_of_intersection_servers)
  return number_of_intersection_servers_;
}
inline void UnionResponse::set_number_of_intersection_servers(::google::protobuf::uint32 value) {
  
  number_of_intersection_servers_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.number_of_intersection_servers)
}

// .union_service.UtilResponse util_response = 14;
inline bool UnionResponse::has_util_response() const {
  return this != internal_default_instance() && util_response_ != NULL;
}
inline void UnionResponse::clear_util_response() {
  if (GetArenaNoVirtual() == NULL && util_response_ != NULL) delete util_response_;
  util_response_ = NULL;
}
inline const ::union_service::UtilResponse& UnionResponse::util_response() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.util_response)
  return util_response_ != NULL ? *util_response_
                         : *::union_service::UtilResponse::internal_default_instance();
}
inline ::union_service::UtilResponse* UnionResponse::mutable_util_response() {
  
  if (util_response_ == NULL) {
    util_response_ = new ::union_service::UtilResponse;
  }
  // @@protoc_insertion_point(field_mutable:union_service.UnionResponse.util_response)
  return util_response_;
}
inline ::union_service::UtilResponse* UnionResponse::release_util_response() {
  // @@protoc_insertion_point(field_release:union_service.UnionResponse.util_response)
  
  ::union_service::UtilResponse* temp = util_response_;
  util_response_ = NULL;
  return temp;
}
inline void UnionResponse::set_allocated_util_response(::union_service::UtilResponse* util_response) {
  delete util_response_;
  util_response_ = util_response;
  if (util_response) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:union_service.UnionResponse.util_response)
}

// uint64 resp_time = 15;
inline void UnionResponse::clear_resp_time() {
  resp_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::resp_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.resp_time)
  return resp_time_;
}
inline void UnionResponse::set_resp_time(::google::protobuf::uint64 value) {
  
  resp_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.resp_time)
}

// uint64 union_time = 16;
inline void UnionResponse::clear_union_time() {
  union_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::union_time() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.union_time)
  return union_time_;
}
inline void UnionResponse::set_union_time(::google::protobuf::uint64 value) {
  
  union_time_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.union_time)
}

// uint64 start_stamp = 17;
inline void UnionResponse::clear_start_stamp() {
  start_stamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::start_stamp() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.start_stamp)
  return start_stamp_;
}
inline void UnionResponse::set_start_stamp(::google::protobuf::uint64 value) {
  
  start_stamp_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.start_stamp)
}

// uint64 end_stamp = 18;
inline void UnionResponse::clear_end_stamp() {
  end_stamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::end_stamp() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.end_stamp)
  return end_stamp_;
}
inline void UnionResponse::set_end_stamp(::google::protobuf::uint64 value) {
  
  end_stamp_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.end_stamp)
}

// uint64 request_id = 19;
inline void UnionResponse::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::request_id() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.request_id)
  return request_id_;
}
inline void UnionResponse::set_request_id(::google::protobuf::uint64 value) {
  
  request_id_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.request_id)
}

// uint64 num_inline = 20;
inline void UnionResponse::clear_num_inline() {
  num_inline_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::num_inline() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.num_inline)
  return num_inline_;
}
inline void UnionResponse::set_num_inline(::google::protobuf::uint64 value) {
  
  num_inline_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.num_inline)
}

// uint64 num_workers = 21;
inline void UnionResponse::clear_num_workers() {
  num_workers_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::num_workers() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.num_workers)
  return num_workers_;
}
inline void UnionResponse::set_num_workers(::google::protobuf::uint64 value) {
  
  num_workers_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.num_workers)
}

// uint64 num_resp = 22;
inline void UnionResponse::clear_num_resp() {
  num_resp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 UnionResponse::num_resp() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.num_resp)
  return num_resp_;
}
inline void UnionResponse::set_num_resp(::google::protobuf::uint64 value) {
  
  num_resp_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.num_resp)
}

// bool kill_ack = 23;
inline void UnionResponse::clear_kill_ack() {
  kill_ack_ = false;
}
inline bool UnionResponse::kill_ack() const {
  // @@protoc_insertion_point(field_get:union_service.UnionResponse.kill_ack)
  return kill_ack_;
}
inline void UnionResponse::set_kill_ack(bool value) {
  
  kill_ack_ = value;
  // @@protoc_insertion_point(field_set:union_service.UnionResponse.kill_ack)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace union_service

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_union_2eproto__INCLUDED
